### ISSUE TITLE
Crash while setting Stats high/low out of bounds

### ISSUE THREAD

**Issue by mountrcg** [Artificial-Pancreas/iAPS#109]
I tried to set the High/Low parameters for the Statsview in release before your latest change to 40-90 and 110-270. When inputing a value outside these boundaries iAPS crashes. Verified on Simulator as well.

**Comment by mountrcg** [comment]
Also iAPS  will keep crashing right after re-start, so I had to un-install and start from scratch with new pod. So potentially nerv wrecking if on pod and away from home with no spare.

**Comment by Jon-b-m** [comment]
I don't understand your first sentence. Are you saying this issue was introduced with latest dev commit or existing in current main branch

**Comment by Jon-b-m** [comment]
What steps does it take to recreate?

**Comment by mountrcg** [comment]
I have double checked, couldn't recreate in dev and I should have tested for this first. It was the use of highGlucose and lowGlucose in ColorofGlucose, which indeed I had adapted when you introduced both variables, as wee had more groups in there earlier. I fixed it in [autoISF commit](https://github.com/mountrcg/iAPS/commit/c224dc86a4751114609c5515af7454a7c56a8b17)
