### ISSUE TITLE
Build/Branch #'s

### ISSUE THREAD

**Issue by dsamuels2300** [Artificial-Pancreas/iAPS#120]
My iAPS build number is stuck on 1 and no Branch number.This has been the case for me for main and dev versions. I just realized this flaw when I saw screenshots of shots of settings in Discord posts.

**Comment by Jon-b-m** [comment]
Please provide as much info as possible when doing an issue report. If you're already using latest version of dev or main you can try doing a new clone or committing or checking out your current branch for the the branch and commit nr to update.

**Comment by Jon-b-m** [comment]
Fix is in dev
