### ISSUE TITLE
Enacted pop-up is obscuring HUD

### ISSUE THREAD

**Issue by bjornoleh** [Artificial-Pancreas/iAPS#13]
I would prefer to be able to se the full context when looking at the enacted pop-up. Most notably, the current BG value is not shown otherwise. This commit, based on a previous commit by @mountrcg might be a potential fix.

Might have to check if this works the same for different phone sizes:

https://github.com/bjornoleh/iAPS/commit/c73a3cd3c1ca588a54f20177c72126ef187d46d5

```
Offset Enacted popup for concurrent view with Header information

based on https://github.com/mountrcg/freeaps/commit/09804413dd1a0ec3e4a0b64dc5ec82250bdc4b9f 
but without opaque pop-up, and the empty box height is adjusted from 90 to 70. 
Works well on iPhone 13 mini, but not tested on other screen sizes.

```
Before:
<img src="https://user-images.githubusercontent.com/63544115/227746022-dd46a20f-2e36-4f6c-a368-cb8f428ee399.png" width="400">

______________

After:
<img src="https://user-images.githubusercontent.com/63544115/227745998-5e16f451-923d-4b7a-8b10-a3695cd8a2c8.png" width="400">

**Comment by Jon-b-m** [comment]
It looks cleaner the way it is. Just from looking at your screenshot gives me a slight headache, it's not pretty. If you want to display more info in enacted box you need to find a more pleasing UI implementation.

**Comment by mountrcg** [comment]
The issue with the overlapping popup is that you do not see current BG, IOB or TempBasal, that was the reason I as a man with a very selective short term memory moved the popup a bit down.

**Comment by Jon-b-m** [comment]
If you create a new PR for this I will test and look at it.

**Comment by sethgagnon** [comment]
closing based on comments above, can review a PR when ready
