### ISSUE TITLE
Display Custom Profile Information in NS (similar to Loop Overrides)

### ISSUE THREAD

**Issue by flyingpie101** [Artificial-Pancreas/iAPS#131]
Feature Request:

Similar to DIY Loop for IPhone.  I would love to be able to visually see or determine what if any Profile Overrides (%) might be in place, in Nightscout.  Ideally this could be shown visually as a bar showing the start and stop time of the override, as well as a Pill under the Time at top left.

I have attached 2 screenshots.  
1 shows the bar at lowest portion of NS display (circled in red).  Is the Override was a preset, then the Presets name could be shown.
![SCR-20230629-de9](https://github.com/Artificial-Pancreas/iAPS/assets/11539494/9585ba0e-5eea-4272-aea8-523396677433)

2nd Screen shows an example of the Override Pill.
![SCR-20230629-de2](https://github.com/Artificial-Pancreas/iAPS/assets/11539494/0dee926b-530a-4196-b510-907f35e11694)

**Comment by francescaneri** [comment]
if it was possible to add the vision of the target as well. happen to use both. Thanks

**Comment by kristianwh** [comment]
In addition to display the active profile, it would be extremely helpful to be able to enable / disable profiles from Nightscout, the same way it can be done for overrides in Loop. For parents  / school managing a child with diabetes this is very helpful, and it could also be used for automation of different profiles.

**Comment by Jon-b-m** [comment]
Now implemented in dev
