### ISSUE TITLE
Merge Nightscout settings

### ISSUE THREAD

**Issue by scrappy** [Artificial-Pancreas/iAPS#140]
A small request ( maybe? )

Can we put all of the Nightscout settings under Nightscout?

Allow Treatments Upload
Allow Glucose Upload
Allow Statistics Upload

I am working with someone on recovering after her phone blew up, and didn't realize how many menu that we needed to go through just to get Nightscout fully populated 😭

Its not often that we have to do something like this, but it would be nice if it was all in one place ...

**Comment by Jon-b-m** [comment]
Pushed to dev branch: https://github.com/Artificial-Pancreas/iAPS/commit/aacfc1325d21d07e700d7a04fea365cb6d05616c
