### ISSUE TITLE
Remote Controls - Announcements stop working after a while

### ISSUE THREAD

**Issue by danielacano** [Artificial-Pancreas/iAPS#143]
### Description
Remote bolus can be sent using the “announcement” event type in NightScout Care Portal as described in the [documentation](https://iaps.readthedocs.io/en/main/settings/configuration/preferences/freeapsx.html#remote-control).
Recent tests have shown that this feature stops working permanently after an uncertain number of successful bolus announcements.
The cause of this issue seems to be associated with a remote bolus announcement that was sent but couldn’t be enacted due to external/unknown factors (like a pump/network error).
While these kinds of errors are expected to happen once in a while, the functionality of the remote bolus announcements is expected to continue working with future announcements after recovering from a failed bolus.

### How to reproduce it
The issue can be reproduced by editing the freeaps/announcements.json and freeaps/announcements_enacted.json files in a way that the latest event (first element) is present only in the first file, but not in the second one.
After that any new remote bolus created in NS will not be enacted.
Example:

**announcements.json**
```
[
  {
    "created_at" : "2023-07-12T11:54:46.092Z",
    "notes" : "Bolus:0.1",
    "enteredBy" : "freeaps-x-remote"
  },
  {
    "created_at" : "2023-07-12T11:43:14.934Z",
    "notes" : "Bolus:0.25",
    "enteredBy" : "freeaps-x-remote"
  }
]
```

**announcements_enacted.json**
```
[
  {
    "created_at" : "2023-07-12T11:43:14.934Z",
    "notes" : "Bolus:0.25",
    "enteredBy" : "freeaps-x-remote"
  }
]
```
![image](https://github.com/Artificial-Pancreas/iAPS/assets/20284380/0e2d13dd-71b1-4773-81e2-7e68e5bc41cf)

### Proposed solution
After some troubleshooting it was detected that when all the announcements are fetched from NS, they are filtered by the latest enacted announcement (what makes sense since already enacted announcements should not be processed more than once) and from there the algorithm selects the most recent once, since only one announcement can be processed in a 10 minutes period of time.
The issue seems to be that instead of selecting the latest one to enact, it actually selects the oldest one, because the order of the elements comes sorted in the opposite way that the algorithm is expecting. This causes that in every new loop the algorithm keeps on picking the same announcement over and over and it can never be enacted because it’s older than 10 minutes.

I'll soon create a PR with my proposed solution. I’ve already tested it with many different scenarios, all tests being successful. That being said, this was my first time reading, debugging and fixing swift code, and I'm also new to iAPS. I can definitely use some help from the community to validate my solution :)

**Comment by flyingpie101** [comment]
I can help with any testing you might need

**Comment by danielacano** [comment]
> I can help with any testing you might need
I've just created the PR for anyone interested in testing: https://github.com/Artificial-Pancreas/iAPS/pull/144
Thank you!

**Comment by flyingpie101** [comment]
Tested Multiple remote boluses - All passed.
Tested remote tempbasal - failed.  none worked. 
a remote bolus functioned even after tempbasal failed.

**Comment by danielacano** [comment]
> Tested Multiple remote boluses - All passed. Tested remote tempbasal - failed. none worked. a remote bolus functioned even after tempbasal failed.

I'll be testing the remote tempBasal today. and will try to understand the issue there. I was so focused in the remote bolus that never tested that one. Thanks for the feedback!

**Comment by Jon-b-m** [comment]
Thanks @danielacano! I've merged your PR for sorting fix into dev branch.

**Comment by bjornoleh** [comment]
Testing this now. Do I have to delete the old announcements.json and announcements_enacted.json files? On first attempt before deleting, the remote bolus did not go through. After deleting both files, it did go through after about 5 minutes, at the next CGM data arrival/loop it seems.

I had an empty announcements.json file, and an announcements_enacted.json file with two old entries in it.

**Comment by bjornoleh** [comment]
On second attempt (which worked, yay!), the bolus went through after two minutes, just before the next CGM reading. Not sure what determines when it goes through, it does not seem to be triggered by GCM data.
