### ISSUE TITLE
Bolus calculator - Hard coded cap 22.3 mmol/L for Eventual glucose make Insulin recommended too low in some cases

### ISSUE THREAD

**Issue by dsnallfot** [Artificial-Pancreas/iAPS#148]
**Description:**
Note: Example in mmol/L and with target 5.5 mmol/L, have not tested if this affects mg/dl also) 
When entering a meal with a carb amount that would make eventual glucose hit the cap 22.3 mmol/L, the "Insulin recommended" in the bolus calculator uses "(22.3-5.5) / ISF" as calculation regardless of the carb amount.

With higher ISF settings (my 6 year old son for instance that have ISF between 17-21 during the day, and CR between 15-25g/U) this makes the bolus calculator recommend a too low bolus at mealtime in almost all cases. Our workaround is off course to enter a bolus amount based on manual calculation, but it would be great if the bolus calculator could be accurate with all kinds of ISF and CR settings.

**Comment by Jon-b-m** [comment]
Agreed. This is a relatively big issue.

**Comment by Jon-b-m** [comment]
Tested raising max to 1000 mg/dl (COBpredBG). However not sure if a limit is really needed, but since this is a rather big change I think we could start with just creasing the upper limit. Pushed to dev branch

**Comment by LiroyvH** [comment]
@Jon-b-m 
Just to be sure, there are (safety) caps on max COB that's taken in to account by OpenAPS right? Eg: it won't take more than 120gr in to account? If so, a limit on CODpredBG might not be necessary. However, if COB could (by accident) be pushed much higher than that (remotely): then some form of safety cap on COBpredBG may be a good idea; perhaps dynamically on ISF/I:C.

**Comment by Jon-b-m** [comment]
We have Max carbs and max COB limit settings already. For CGM readings we have a upper and a lower limit and a noise setting and a max glucose delta setting for SMBs and a flat glucose check for bad sensors, but we can never be fully protected against bad CGM readings unfortunately.
