### ISSUE TITLE
Logging 0U to Apple health

### ISSUE THREAD

**Issue by LiroyvH** [Artificial-Pancreas/iAPS#149]
I noticed in the data portion of health that iAPS is logging tons of “0 units” basal to Apple Health. I’m not sure if that’s intentional, but imho it’s rather useless as Apple Health doesn’t deal with temp basals or anything; only records total doses, TDD and average. Therefore this is, imho, unnecessarily generating a lot of data in the health app that’s taking up space needlessly.

![image](https://github.com/Artificial-Pancreas/iAPS/assets/4643445/ee9b74f3-24bc-4523-a08b-e978504cb586)

**Comment by avouspierre** [comment]
Fix the issue with a best management of data pushed by iAPS in HK

**Comment by LiroyvH** [comment]
Looks good in latest dev, thanks! Now basal counting within Health seems to be more accurate as well.

**Comment by sethgagnon** [comment]
closing as this was pushed to dev
