### ISSUE TITLE
"Feature Request" allowing adjustment of SMB/UAM basal minutes in TT (overrides)

### ISSUE THREAD

**Issue by Danielsloop** [Artificial-Pancreas/iAPS#152]
I was wondering  if there is a possibility in Temporary targets to also allow adjustment of SMB and UAM basal minutes. For people with basals lower than 0.3 to be able to allow iAPS to run for a short period with higher SMB/UAM for large carb meals. Giving the opportunity to run almost FCL.

**Comment by Jon-b-m** [comment]
This is possible to do with a profile.
