### ISSUE TITLE
Add euglycemic range TIR to statistics

### ISSUE THREAD

**Issue by scrappy** [Artificial-Pancreas/iAPS#154]
In order to make it easier to compare TIR between patients, including the euglycemic TIR values as part of statistics would be nice

TIR %ages ( median ) would drop as a result, since its a tighter range, but I can add that range to the full_list.php page as well, so that when comparing an individuals TIR to the group median, they would be able to compare apples to oranges, *as well as* seeing their TIR % based on their personalized range ...

**Comment by Jon-b-m** [comment]
Request completed and has been pushed to dev branch
