### ISSUE TITLE
statistics.json -> HbA1c

### ISSUE THREAD

**Issue by scrappy** [Artificial-Pancreas/iAPS#156]
latest dev code with the euglycemic stored in statistics.json seems to be mis-reporting Hba!c as 0:

```
     "Statistics": {                          +
         "HbA1c": {                           +
             "day": 0,                        +
             "week": 0,                       +
             "month": 0,                      +
             "total": 46.7                    +
         },
```

My Statistics view looks right, so it doesn't look like a data lose after last upgrade ... just zero values for those fields ... checked yours two, as you are reporting Euglycemic values too, same ... day/week/month all 0, total is 46.7 ( other scale, obviously ) ...

**Comment by Jon-b-m** [comment]
Fix in dev
