### ISSUE TITLE
Apple Watch Required Insulin with color font

### ISSUE THREAD

**Issue by timwa124** [Artificial-Pancreas/iAPS#157]
Hi,
our son is using iaps a long time and is really happy so far. since a few weeks iAPS highlights the required insulin dose in RED if the prediction would cause in a low BG. Would it be possible to add this feature to apple watch as well?
Currently the Apple Watch value recommends insulin but in some cases we should wait for a while. 
Thanks best MArkus

**Comment by Jon-b-m** [comment]
pushed to dev
