### ISSUE TITLE
Lower I:C

### ISSUE THREAD

**Issue by LiroyvH** [Artificial-Pancreas/iAPS#158]
It appears the carb ratio has a minimum value of 1u:3gr. I'm not sure if this limit was chosen by some design (couldn't find anything about it), but I for example need it to be lower. Was wondering if there's no particular reason for a cap of 3, if it could be removed. I found that modifying the json to a lower number simply reverts back to 3.

**Comment by Jon-b-m** [comment]
I guess it was added as a safety measure, avoiding inadvertently entering too low carb ratios. It's hard coded in FreeAPS/Sources/Modules/CREditor/CREditorStateModel.swift, line: 
let rateValues = stride(from: 30.0, to: 501.0, by: 1.0).map { ($0.decimal ?? .zero) / 10 }

**Comment by Jon-b-m** [comment]
What ratio do you need?

**Comment by LiroyvH** [comment]
@Jon-b-m 
Thanks! Maybe a better option would be not to limit it, but to ask for confirmation if the user is sure - much like when you want to bolus but it predicts you'll go low. 

I'm currently looking at 1:2.0 in the evening and 1:2.5 in the morning/afternoon. I hope I won't need to go any lower. :/ This ratio is annoying enough as it is. :P (Use too much for Omnipod :()

**Comment by Jon-b-m** [comment]
OK, so lowering it to 1 would be an easy fix then...

**Comment by Jon-b-m** [comment]
Fix here in dev https://github.com/Artificial-Pancreas/iAPS/commit/9bc38cf30637e7e165905e31c368bfb852f1f23f
