### ISSUE TITLE
Feature Request: Have iAPS write profile information to the Nightscout Profile

### ISSUE THREAD

**Issue by flyingpie101** [Artificial-Pancreas/iAPS#164]
Nightscout has a Profiles section (Profile Editor), that can store profile changes.

Using Loop as an example, if the "Normal" or Base profile in Settings are changed, then a new Profile is created and uploaded to NS with a Record Valid from current date.
1. This allows people to view the history of Profile changes
2. Allows caregivers to check on profile settings when access to T1D phone is not readily available
3. There might be downstream benefits to NS reporting, not sure about that though

This is a lesser priority, but still useful (in my opinion)

**Comment by scrappy** [comment]
This already happens and is visible in Nightscout's Profile Editor ... I just double checked my NS to make sure ... is there something missing with what is there now?

**Comment by Jon-b-m** [comment]
This is in dev now
