### ISSUE TITLE
Ability to push up new statistics manually ...

### ISSUE THREAD

**Issue by scrappy** [Artificial-Pancreas/iAPS#185]
On the Settings -> Nightscout Config screen, having a 'button' mirroring 'Backfill glucose' that allows someone to force an update of statistics / preferences would be great.

99.9% of the time, "once a day" is fine, but when looking at / debugging settings with someone else, being able to get more up to date data is helpful, especially if a case manager / doc in the office wants to confirm that a patient has properly applied changes, if needed.

**Comment by Jon-b-m** [comment]
Preferences and settings are now automatically uploaded when changed and can also be manually pushed.
