### ISSUE TITLE
Endless loop on bad custom peak times: error handling optimisations

### ISSUE THREAD

**Issue by LiroyvH** [Artificial-Pancreas/iAPS#188]
A built-in (security) limit sets the minimum peak-time when rapid-acting is selected to 50 minutes. I had accidentally forgot to turn to ultra-rapid but had set the custom peak-time (to 45 for Lyumjev). As a result, I had the configuration "Rapid-acting, custom peak-time: 45 minutes". Which OpenAPS doesn't like as it demands a 50-minute minimum. This leads to an endless loop (spinning wheel "Looping") and hundreds of thousands of lines of log-output in a short period of time (+/- 200 log-entries per second). 

The information pop-up for that setting explicitly warns for issues such as this, so no worries there - this is completely my fault and a bad result is expected; so no complaints there. However, I do think the error-handling can be better - which is why I decided to raise an issue here anyway. It generates thousands and thousands of lines of errors in the logs (which very rapidly grows in size) whilst not reporting an error under the loop button, eg:
> 2023-08-22T11:39:00+0200 [OpenAPS] JavaScriptWorker.swift - createContext() - 23 - DEV: JavaScript log: Setting minimum Insulin Peak Time of 50m for,rapid-acting,insulin
> 2023-08-22T11:39:00+0200 [OpenAPS] JavaScriptWorker.swift - createContext() - 23 - DEV: JavaScript log: Setting minimum Insulin Peak Time of 50m for,rapid-acting,insulin
> 2023-08-22T11:39:00+0200 [OpenAPS] JavaScriptWorker.swift - createContext() - 23 - DEV: JavaScript log: Setting minimum Insulin Peak Time of 50m for,rapid-acting,insulin
> 2023-08-22T11:39:00+0200 [OpenAPS] JavaScriptWorker.swift - createContext() - 23 - DEV: JavaScript log: Setting minimum Insulin Peak Time of 50m for,rapid-acting,insulin
> 2023-08-22T11:39:00+0200 [OpenAPS] JavaScriptWorker.swift - createContext() - 23 - DEV: JavaScript log: Setting minimum Insulin Peak Time of 50m for,rapid-acting,insulin
> 2023-08-22T11:39:00+0200 [OpenAPS] JavaScriptWorker.swift - createContext() - 23 - DEV: JavaScript log: Setting minimum Insulin Peak Time of 50m for,rapid-acting,insulin
> 2023-08-22T11:39:00+0200 [OpenAPS] JavaScriptWorker.swift - createContext() - 23 - DEV: JavaScript log: Setting minimum Insulin Peak Time of 50m for,rapid-acting,insulin
> 2023-08-22T11:39:00+0200 [OpenAPS] JavaScriptWorker.swift - createContext() - 23 - DEV: JavaScript log: Setting minimum Insulin Peak Time of 50m for,rapid-acting,insulin
> 2023-08-22T11:39:00+0200 [OpenAPS] JavaScriptWorker.swift - createContext() - 23 - DEV: JavaScript log: Setting minimum Insulin Peak Time of 50m for,rapid-acting,insulin
> 2023-08-22T11:39:00+0200 [OpenAPS] JavaScriptWorker.swift - createContext() - 23 - DEV: JavaScript log: Setting minimum Insulin Peak Time of 50m for,rapid-acting,insulin

EndlessLoop » grep "Setting minimum Insulin Peak Time of 50m for,rapid-acting,insulin" ./* | wc -l
:: 272949

Figured the handling of this configuration fault could perhaps be optimised? As in: do not log the same error so many times in succession, abort the loop and/or show under the (red) loop button in the status area a notice that the configuration is unacceptable. Or simply don't allow this combination of settings to exist and make it error out in app when trying to do that, that might also work. :P 

Again, setting the configuration this way is my own fault and the information pop-up properly warns for it. But making the mistake should, imho, not lead to such excessive repetition of log entries and the absence of an error under the loop status is something that may be nice to improve as well. :) 

Thank you for your consideration.

**Comment by Jon-b-m** [comment]
Yeah, I'm surprised you're seeing this issue now, as it should have ben fixed a long time ago with a merged commit from oref0 fixing this...

Will take a look at this later...

Thanks for reporting

**Comment by Jon-b-m** [comment]
Fix is now in dev branch!
