### ISSUE TITLE
Simplify prediction graphs

### ISSUE THREAD

**Issue by scrappy** [Artificial-Pancreas/iAPS#190]
Someone posted this on discord, and I've also heard this from case managers at clinic ... honestly, no idea if this is something that would be even possible, but somehow consolidate the various prediction graphs into one that somehow makes sense?

Biggest complain that the case managers have is understanding of the various graphs and what to do with them ... where Loop is nice and simple and only as the one ( and the one prediction as well, so graphing it is easy ) ...

I'm just throwing it out here since it has been mentioned on discord ... maybe someone has some idea on how such could be implemented *shrug*

**Comment by Chester-sk8** [comment]
Great idea
