### ISSUE TITLE
Bug 2.2.3- DynISF Sigmoid Fails to Update ISF Baseline When Profile Target BG Changes

### ISSUE THREAD

**Issue by FlorinBv** [Artificial-Pancreas/iAPS#192]
I've found a bug related to DynamicISF and the Sigmoid function. When a temporary target is activated, the ISF baseline adjusts to the new target as expected. However, this adjustment doesn't occur when a profile with a different target is activated.

Case Example Scenarios:

**Case 1
Profile with BG Target = 130**
Default BG Target = 100
ISF = 50
Sigmoid = Activated
New ISF at BG 122 becomes 50 -> 46. This shows that the BG reference for initiating the ISF calculation remains at BG 100, ignoring the new target from the activated profile.

**Case 2
Temp Target BG = 130**
Default BG Target = 100
ISF = 50
Sigmoid = Activated
New ISF at BG 122 becomes 50 -> 52. This indicates that the BG reference for initiating the ISF calculation is BG 130.

Screenshots have been attached for further reference.

<img width="1867" alt="Screenshot 2023-08-26 at 14 31 39" src="https://github.com/Artificial-Pancreas/iAPS/assets/50909401/c5f3b002-02fb-45cc-9396-c64129d0c8fb">

**Comment by Jon-b-m** [comment]
Yes, correct. Thanks! I will fix it tomorrow.

**Comment by Jon-b-m** [comment]
Fix pushed to dev. Please test. Will close issue after some more testing...
