### ISSUE TITLE
Decimals not visible in saved Profiles title

### ISSUE THREAD

**Issue by ViTuDia** [Artificial-Pancreas/iAPS#195]
When saving a profile the number behind the comma is not shown in the overview of saved profiles. 

Like this it is not clear what the exact target is. Target 8 could be 8,0 or 8,9 etc. 

![IMG_0676](https://github.com/Artificial-Pancreas/iAPS/assets/59163092/50ddbd09-f2c8-4318-bb61-e35abec9f410)

**Comment by Jon-b-m** [comment]
Fix pushed to dev. Please test.

**Comment by ViTuDia** [comment]
Works fine now!
