### ISSUE TITLE
Request: one menu option for “overrides”

### ISSUE THREAD

**Issue by ViTuDia** [Artificial-Pancreas/iAPS#196]
Is it an idea/option to have one place for profiles/targets/overrides?

Right now the app provides Temp Targets with some limited possibilities for changes. 

There is also the section with profiles with very many possibilities for changes. 

Why the section of Temp Targets still exists?

Could a name change help?
For example: change the menu name “Profiles” to “Overrides“ (or whatever) and replace and eliminate the Temp Targets menu. So it is not about “profiles” or “temp targets”. It is about overriding the current settings for a limited time or indefinitely.

**Comment by sethgagnon** [comment]
Closing profiles exist now as well
