### ISSUE TITLE
low prio issue: log formatting issue, not on the same line

### ISSUE THREAD

**Issue by antoinekh** [Artificial-Pancreas/iAPS#197]
Hello,

Issue on the log formating for autosens. The values should be in the same log line in my opinion 

![image](https://github.com/Artificial-Pancreas/iAPS/assets/52744345/90c014f4-79bf-4aed-8a06-1faa6840a7b1)

Log file for example:

[log.txt](https://github.com/Artificial-Pancreas/iAPS/files/12452761/log.txt)

**Comment by Jon-b-m** [comment]
Hmm, yes this looks weird. Thanks!

**Comment by Jon-b-m** [comment]
These logs are now removed
