### ISSUE TITLE
Dexcom G6 SAGE is not updated in NS

### ISSUE THREAD

**Issue by bjornoleh** [Artificial-Pancreas/iAPS#198]
@trixing added the feature of updating SAGE in NS for Dexcom G6 and LibreTransmitter in this feature branch:

https://github.com/trixing/freeaps/commits/patch/sage

This was merged with ivalkou freeaps at some point (and also with the previous fork of @Jon-b-m that is now iAPS)

This is the diff for the relevant commits:
https://github.com/trixing/freeaps/compare/master...trixing:freeaps:patch/sage

One of the files that were involved in the SAGE feature was part of managing the the G6 driver from Loop: 
https://github.com/trixing/freeaps/blob/patch/sage/FreeAPS/Sources/APS/CGM/DexcomSource.swift

This file got deleted when updating the various Loop dependencies after Loop 3.0 was released. A lot of this code had been refactored since it was first included in FreeAPS X / iAPS, and @avouspierre probably had to make significant changes when importing the updated drivers. 

Unfortunately, the SAGE feature for G6 has been broken since this. It would be nice if someone could understand how to bring this feature back.

**Comment by avouspierre** [comment]
@bjornoleh  do you know if Loop 3 has a correct implementation of SAGE feature ?

**Comment by bjornoleh** [comment]
It's not in Loop yet, but the loop and learn team have prepared a patch that users can apply using their build script. I think this is the patch for Loop dev: https://github.com/loopandlearn/customization/blob/main/dexcom_sage/dev_g6g7_sage.patch

**Comment by avouspierre** [comment]
Ok. But as always, not very agree to modify the loop code. Better if loop team included this patch in their branch.

**Comment by bjornoleh** [comment]
Absolutely! Perhaps @bjorkert can comment on whether or not it is likely that the SAGE (and CAGE) patches for Loop will make it into Loop dev? I don't think there is a PR for it yet.

**Comment by bjorkert** [comment]
The existing code is not destined for PR/integration into the Loop. It has been optimized for use as patches, aiming to keep them isolated and minimize the fingerprint to prevent conflicts. As of now, I'm not aware of any ongoing efforts to implement CAGE/SAGE uploads in Loop.

**Comment by bjornoleh** [comment]
@avouspierre , the FreeAPS/Sources/APS/CGM/DexcomSource.swift file was as I understand it not part of the Loop code, so we could potentially recreate a similar solution as before without touching Loop code:

https://github.com/trixing/freeaps/commit/2c12c4324454a688f49371f8f776dd9af6f54583

The reason this file got deleted is that there are now two files, one for G6 and one for G7. They are a little refactored, and I have not been able to just drop in the original changes from trixing:

https://github.com/Artificial-Pancreas/iAPS/blob/dev/FreeAPS/Sources/APS/CGM/DexcomSourceG6.swift

https://github.com/Artificial-Pancreas/iAPS/blob/dev/FreeAPS/Sources/APS/CGM/dexcomSourceG7.swift

**Comment by bjorkert** [comment]
These patches has their own upload code to Nightscout, instead of passing this information into the normal Loop flow of information to Nightscout.

**Comment by bjornoleh** [comment]
I haven't been able to test, but hopefully this will work for G6. Or at least possibly on the right track. G7 has not been considered yet, but might be similar. LoopKit dependencies are not modified here.

Anyone willing to test? It does not have to coincide with changing the sensor.

https://github.com/bjornoleh/iAPS/commit/e0922b7b184e848f2e9f4c6b5e10807b8b1c4418

**Comment by bjornoleh** [comment]
I have a fix for this now, where SAGE is updated like it used to be before we updated Loop dependencies. 
PR opened: https://github.com/Artificial-Pancreas/iAPS/pull/212

**Comment by avouspierre** [comment]
@bjornoleh the code is done with the hypothese of latestReading is always fulfil. If not (value = empty / nil), the BloodGlucose will not record and will not be use by iAPS. I didn't go in the detail to check this hypothese but probably you can prevent the null of activationDate and  sessionStartDate but allowing to record a BG value.

**Comment by bjornoleh** [comment]
> @bjornoleh the code is done with the hypothese of latestReading is always fulfil. If not (value = empty / nil), the BloodGlucose will not record and will not be use by iAPS. I didn't go in the detail to check this hypothese but probably you can prevent the null of activationDate and sessionStartDate but allowing to record a BG value.

Thanks!

Do you propose I change something in these lines of the PR?

https://github.com/bjornoleh/iAPS/blob/5cb4445981058f2cdd0ba2e940952e6e92e0089d/FreeAPS/Sources/APS/CGM/DexcomSourceG6.swift#L148C13-L151C14

```
if let cgmG6Manager = cgmManager as? G6CGMManager,
               let activationDate = cgmG6Manager.latestReading?.activationDate,
               let sessionStartDate = cgmG6Manager.latestReading?.sessionStartDate
            {
```

**Comment by avouspierre** [comment]
OK if you are sure, that's ok for me.

**Comment by bjornoleh** [comment]
Ok, thanks! If you think it looks good, perhaps you can merge the PR :-) Jon was just waiting for our review.
