### ISSUE TITLE
Autotune calculations inconsistent

### ISSUE THREAD

**Issue by jmatheson** [Artificial-Pancreas/iAPS#199]
Using iAPS in Autotune there is a ‘run now’ action. If I press that 3 times in a row it recalculates all of my basals to different values each time. The same data set should Autotune to the same results unless I am missing something.

**Comment by jmatheson** [comment]
Tried again a few days later as I have more time on iAPS. This time swapping between to value sets.https://github.com/Artificial-Pancreas/iAPS/assets/9138265/05853f58-a989-454e-a3e5-df232f4fdc0d

**Comment by Jon-b-m** [comment]
AT is supposed to run once every night, looking back (using real  data) at up to 24 hours. AT is limited to changing the current settings at a max of 20 %. But if you run it 3 times in row you're not using real data anymore and also sort of  exceeding the 20 % limit. This is not recommended.
