### ISSUE TITLE
Experimental TempTarget not always working / Rounding Issues 

### ISSUE THREAD

**Issue by mountrcg** [Artificial-Pancreas/iAPS#20]
I have tested the new TempTarget with adjustable HalfBasalTarget functionality extensively. It often falls back to the HBT from preferences instead the one from the oref2_variables:
Desired set ratio 50% with TT 180, which should set HBT at 180.

- loop was calculated
- Variables are saved properly in oref2_variables, is enabled true and hbt at 180
- but autosens reports 33% instead of 50%, 33% would be calculated if HBT set at 140, which is the current value in preferences

Dev Branch, latest commit / TT set in Experimental / Popup after 1st Loop / fielecontent oref2_variables
<img src="https://user-images.githubusercontent.com/539276/229986545-7be85e02-6969-4c33-9f50-e6b1a6cb3334.png"  width=250 /> <img src="https://user-images.githubusercontent.com/539276/229987304-bd3f0eb4-162c-4196-a013-b6ab98c37890.png"  width=250 /> <img src="https://user-images.githubusercontent.com/539276/229987614-0b8061e9-2eb5-4185-b6d7-24e1b21bdb58.png"  width=250 /> <img src="https://user-images.githubusercontent.com/539276/229987779-eed2f7e0-042c-4ddf-afd1-183d4dec8ac5.png"  width=250 /> <img src="https://user-images.githubusercontent.com/539276/229987950-9e314a33-e61d-4259-b5cf-cc73c2bc8dc6.png"  width=250 />

I cannot ascertain what the problem is, as I also observe proper setting of the Insulin ratio with the TempTarget SensitivityRatio being calculated with the correct HBT. However as @Jon-b-m  chooses not to publish Oref Source code there is nothing I can do at the moment to help fix this.

It's easiest tested with Ratios set to 50% as TempTarget will be the same as Halb Basal Exercise Target setting.

However to more easily analyze this issue I will put forward 3 PR's. Non of those PR's fixes the issue, though.
1.) show the TT based Sensitivity adjustment in InfoPanel besides the TempTarget -> #21 

2.) fix rounding issues that outputs calculation results of mg/dL TempTargets with 1 digit and also with 2 digits with both measurement units in the history if one switches units in Preferences -> #22 
<img src="https://user-images.githubusercontent.com/539276/229989217-6d4a8459-d3c7-49c3-a431-200190b2742d.png"  width=250 /> <img src="https://user-images.githubusercontent.com/539276/229989436-7f77f49d-f9de-41e1-be4d-e5ba42bead97.png"  width=250 />

3.) another UI solution that improves on usability and easyness in my view -> #23

**Comment by mountrcg** [comment]
rounding issue PR'ed in #21

**Comment by mountrcg** [comment]
were you able to verify the error, I can always re-create it on simulator?

**Comment by Jon-b-m** [comment]
There is a small delay, same which exists for weighted averages. But delay exist in the json you posted here. To fix this the entire oref0 swift implementation in iAPS needs to be rewritten, which I will at some point, but haven’t had time for yet. 
There are also several bugs with the simulator. The current  simulator isn’t complete, unfortunately, which makes the simulator to an  incomplete testing environment.

**Comment by mountrcg** [comment]
if you could post the oref code as it is atm I could test properly and also continue with my stuff. I have re-worked some of it as I thought you did, but the Overrides I can't recreate without much hassle

**Comment by Jon-b-m** [comment]
TTs are using Master oref0 code 0.7.1 as is. The required code modification for overrides I have already posted to you

**Comment by Jon-b-m** [comment]
And since this post is again apparently is for you wanting help with updating your autoISF branch I will now close it.
