### ISSUE TITLE
Enable Dynamic CR stand alone does not work

### ISSUE THREAD

**Issue by ViTuDia** [Artificial-Pancreas/iAPS#200]
When toggled Enable Dynamic ISF AND Enable Dynamic CR both ISF and CR change to a dynamic value the next loop. 

When ONLY Enable Dynamic CR is toggled, suddenly the CR value does not change the next loop, neither in the future. It stays the CR value as given in the setting of the Carb Ratios. 

When Enable Dynamic CR is toggled it should recalculate CR, not only when Enable Dynamic ISF is toggled as well.

**Comment by Jon-b-m** [comment]
Yes, currently dynamic CR (and dynamic basal) is only activate together with dynamic ISF. This is because first we only had dynamic ISF. CR and basal were added later as optionals.

**Comment by Jon-b-m** [comment]
Does anyone need dyn CR only?

**Comment by Jon-b-m** [comment]
Fixed in latest dev branch
