### ISSUE TITLE
Feature Request: Add option to disable UAM for 'X' amount of time if glucose hits 'Y'

### ISSUE THREAD

**Issue by tqb43** [Artificial-Pancreas/iAPS#201]
To avoid hypo treatment related UAM spikes. I thought it would be cool if there was an option to turn UAM off automatically if a glucose hits a certain level, X, and then turn back on after Y amount of minutes.

**Comment by Jon-b-m** [comment]
I think it's better you test this in middleware first. Then if you find your experimental code good and helpful we could consider adding it to the dev repo for more testing.

**Comment by sethgagnon** [comment]
Closing based on comments above. Can open a PR when code is ready for review
