### ISSUE TITLE
Using Apple Health / Watch exercise information for Basal/Bolus prediction

### ISSUE THREAD

**Issue by degola** [Artificial-Pancreas/iAPS#211]
It would be great if the exercise records in Apple Health, in my case coming from the Apple Watch, could be automatically used for auto-tune basal and bolus as well as food bolus calculations.

In my case my blood glucose seems to start dropping ~15 minutes after starting exercising and continues to do so for an hour after exercising while I can use the higher temp target setting I tend to forget setting it regularly so taking it automatically from my Apple Watch (which detects starting to exercise automatically + intensity even at some point) would be great.

Happy to contribute code as well but unfamiliar with the source code and lack of time, if there is somewhere an high-level code architecture available that would be great :-).

p.s.: the discord link is broken/outdated in the README.md

**Comment by avouspierre** [comment]
You can use shortcuts to do this. Create a shortcut with an automation on fitness workout and apply a temporal profile. A example in the screenshots 

![image](https://github.com/Artificial-Pancreas/iAPS/assets/4339604/446d8b68-7d52-4c41-b913-85a275e126bc)

![image](https://github.com/Artificial-Pancreas/iAPS/assets/4339604/bfed56af-a644-4cc9-88b9-8efbee01e717)

**Comment by LiroyvH** [comment]
@avouspierre That's pretty cool! I didn't even know it was compatible with the Shortcuts app. 
Question: in your example, am I correct in understanding that it won't switch to temporary profile when BG is over 180?

**Comment by jmatheson** [comment]
Any plans for a way to set a profile via shortcuts? Temp target is nice but profile would be 💰

**Comment by LiroyvH** [comment]
@jmatheson I don't think there are plans perse yet, no concrete anyway, but I did make a feature request: https://github.com/Artificial-Pancreas/iAPS/issues/255

**Comment by sethgagnon** [comment]
Closing this issue as the shortcut instructions are mentioned above

**Comment by sethgagnon** [comment]
Closing this issue as the shortcut instructions are mentioned above
