### ISSUE TITLE
Discord links in documentation seems out of date or invalid

### ISSUE THREAD

**Issue by PieterGit** [Artificial-Pancreas/iAPS#214]
There are two different Discord links mentioned in the documentation. Both don't seem to work. Is there still an active discrod channel for this project?

https://iaps.readthedocs.io/en/main/operate/build.html mentions https://discord.gg/xfnxYaBG

https://iaps.readthedocs.io/en/main/resources/citations.html and  https://github.com/Artificial-Pancreas/iAPS mention
https://discord.gg/2gBpxRT2g

I can provide pull request to change the docs if somebody helps me with a working Discord invite linke.

Thanks.

Pieter

**Comment by Jon-b-m** [comment]
https://discord.gg/ceCtY2s48
