### ISSUE TITLE
Suspend Zeros IOB set true but should be false by default. 

### ISSUE THREAD

**Issue by ViTuDia** [Artificial-Pancreas/iAPS#217]
The explaination text says by default false, actually this setting is set true by default, after a fresh install of the app. 

![IMG_1057](https://github.com/Artificial-Pancreas/iAPS/assets/59163092/f9035ca0-80db-4c6e-8361-db891e8a3288)

**Comment by Jon-b-m** [comment]
This was fixed some time ago. Testing new build of main branch  in simulator displays as off.  Did you really delete the old app before testing installing anew?

**Comment by ViTuDia** [comment]
Probably my mistake. I installed the app fresh the 25th of August. By that time the default was true. I was encountering this message lately. 

If it is fixed it is fixed and my issue can be closed.
