### ISSUE TITLE
Calendar access for iAPS on 2.2.5

### ISSUE THREAD

**Issue by mjvelascoCLS** [Artificial-Pancreas/iAPS#218]
No calendar access for iAPS for newly published version 2.2.5 using iPhone 15.. but calendar is fine with iPhone 14, both phones have iOS 17 installed..

**Comment by igorburenko** [comment]
Same here

**Comment by igorburenko** [comment]
To fix. 
1. Go to the settings->privacy and security->calendars
2. Find iaps in the list. tap on icon
3. Allow full access to calendars

**Comment by mjvelascoCLS** [comment]
That’s the problem cos I don’t see iAPS there under calendar to give full access to..

**Comment by Jon-b-m** [comment]
A fix is in dev branch
