### ISSUE TITLE
Wait with health sync until bolus completion

### ISSUE THREAD

**Issue by LiroyvH** [Artificial-Pancreas/iAPS#231]
When a bolus is administered and halfway through you get a pump error, iAPS writes the proper value (what was actually delivered) to its history and to Nightscout. However, to Apple Health: it syncs the original input amount (what was requested) instead, rather than what was delivered. 

It'd be nice if iAPS could wait with syncing to health until the final delivery amount is determined, so iAPS, Nightscout and Apple Health all have the same value. Also, shameless plug to ask for a fix for #149 as it generates a lot of data. (Or if it's by design: a toggle to stop syncing (zero-)basal to Apple Health)

**Comment by avouspierre** [comment]
Fix the issue with a best management of data pushed by iAPS in HK
