### ISSUE TITLE
red loops.. 

### ISSUE THREAD

**Issue by mjvelascoCLS** [Artificial-Pancreas/iAPS#233]
there seems to be a drop in connection with dexcom and iAPS..? I've had this happened at least 4 times now randomly.. one time I didnt notice I had a red loop for more than two hours.. my workaround for this issue is to enter BG through the health app and seems to connect and loop again.. 

2.2.5 iPhone 15 pro Max with dexcom G7

**Comment by avouspierre** [comment]
You need to have more information to be able to analyze your red loop. Do you have logs during this red loop?
