### ISSUE TITLE
Differentiate Between Auto and Manual Boluses on History List

### ISSUE THREAD

**Issue by lasercow99** [Artificial-Pancreas/iAPS#275]
Could manual boluses be marked on the History Treatments list? A few times I have gone low and it's been my fault for not waiting for iAPS to do it's thing, and I've given the suggested bolus. On reviewing the history, it would be easier see manual and automatic boluses, to analyse what was going on.

**Comment by LiroyvH** [comment]
This is currently implemented in dev branch
