### ISSUE TITLE
(De facto) Remote control with carb inputs whilst remote control is disabled

### ISSUE THREAD

**Issue by LiroyvH** [Artificial-Pancreas/iAPS#278]
Not sure if it ought to be considered an issue, but it's always surprised me a bit that it works this way. So opening an issue for discussion/perhaps additional (optional) security measures:

iAPS imports carb entries from Nightscout and adds them to the COB on the next loop. It adjusts predictions accordingly and under some circumstances it may start (significantly) raising basal or starts administering SMB's (or enables SMB for people who have it set to enable "after carbs" or "with COB"). Abstractly, you could argue that this is a form of Remote Control. This works whilst Remote Control is disabled in the iAPS settings - iAPS will accept the entered carbs and act accordingly. Of course also the bolus suggestions and such change.

I personally do not want Remote Control for boluses enabled, but I find adding carbs through NS to be extraordinary useful as I use another app that contains my Food Database to calculate all carbs, feed them (no pun intended) to Nightscout and iAPS subsequently imports them. Super useful. So I like "remotely" entering carbs, but do not want the ability to remotely bolus (despite my Nightscout not even being available on the internet.). (So by opening this issue I might be shooting myself in the foot, but safety first. :P) 

From a security perspective, imho, you:
1.) Should first have to enable Remote Control before iAPS will accept carbs from NS to be taken in to account
2.) But ideally: there will be an option to only accept carbs or to accept carbs *and* remote bolus.

**Comment by Jon-b-m** [comment]
I don't think we need more settings. 
The adding carbs from Nightscout has been used since the day of FreeAPS X and is used by many users. I don't think we need to limit this feature with an added setting. I agree it's convenient to use with shortcuts .

**Comment by LiroyvH** [comment]
Ok, then maybe we just need to add a note in the documentation that this could be a problem on open Nightscout instances. (Along with the other issues having it open on internet facing servers :P)
