### ISSUE TITLE
Profile Preset SMB/UAM minutes are ignored

### ISSUE THREAD

**Issue by dnzxy** [Artificial-Pancreas/iAPS#284]
User Kmac has reported on Discord

> I have a possible issue with a saved Profile.  This temp profile is intended to temporarily set a higher SMB and UAM minutes from 60 minutes to 120 minutes.  Basal at this time was .4 so I’d expect a .8 MaxBolus. Note that in the attached pic the selected Profile indicates both SMB/UAM are set to 120.  However, these  weren’t applied. In the Loop pop up, maxBolus shows a .4 which would be 60 minutes.  When I opened the Profile screen, SMB/UAM minutes toggles were set to 60 instead of 120 even though slider was at 101% and profile time was running down as expected.  Is there anything I am missing that would have these at 60 or limit maxBolus? v2.2.4-3 Main. Pics and logs attached 

> I deleted all saved profiles with increased UAM minutes.  I enacted a new profile from scratch with increased UAM minutes which worked. I then saved  that profile, returned to Normal and enacted the Saved profile. This repeated the error.  Looks to me like increases to SMB/UAM minutes are not working in saved Profiles. Can anybody confirm?

| Screenshots | &nbsp; |
|--------|--------|
| ![image](https://github.com/Artificial-Pancreas/iAPS/assets/48965855/7ac3b45d-2d3c-464e-8cd1-6912280e8acb) | ![image](https://github.com/Artificial-Pancreas/iAPS/assets/48965855/1e5629f1-4a35-4a41-b852-f8e1adee4c50) | 

Provided logs:
* [log_prev.txt](https://github.com/Artificial-Pancreas/iAPS/files/13188544/log_prev.txt)
* [log.txt](https://github.com/Artificial-Pancreas/iAPS/files/13188546/log.txt)

---

I have checked in `FreeAPS/Sources/Modules/OverrideProfilesConfig/OverrideProfilesStateModel.swift`. It looks like we always override the entered minutes with the minutes that are saved via Settings > Preferences > Max SMB Minutes / Max UAM Minutes:
* Lines 71+72 and 114+115 on saving a preset 
* Lines 154+155 when retrieving / enacting a preset

**Comment by Jon-b-m** [comment]
Fix is in dev. Please update and recreate your profiles, if needed.
