### ISSUE TITLE
Incorrectly identifying SMBs as manual boluses.

### ISSUE THREAD

**Issue by JohnKitching** [Artificial-Pancreas/iAPS#288]
Dev 2.2.6
![image](https://github.com/Artificial-Pancreas/iAPS/assets/48366213/e13b80fd-981f-494a-9cc8-5d72f045d585)

**Comment by dnzxy** [comment]
Thanks to John for providing these log files on Discord:
* [log.txt.txt](https://github.com/Artificial-Pancreas/iAPS/files/13198989/log.txt.txt)
* [log_prev.txt.txt](https://github.com/Artificial-Pancreas/iAPS/files/13198990/log_prev.txt.txt)
* [pumphistory-24h-zoned.json](https://github.com/Artificial-Pancreas/iAPS/files/13198991/pumphistory-24h-zoned.json)

**Comment by dnzxy** [comment]
From your logs

* SMB 0.2u at 13:53, displayed as SMB, automatic dose

> 2023-10-29T13:53:30+0000 [OpenAPS] OpenAPS.swift - determineBasal(currentTemp:clock:) - 80 - DEV: SUGGESTED: {"temp":"absolute","bg":132,"tick":"+2","eventualBG":279,"insulinReq":0.23,"reservoir":37.35,"deliverAt":"2023-10-29T13:53:30.057Z","sensitivityRatio":1.0923550125843062,"CR":8.2,"TDD":73.75,"insulin":{"TDD":73.75,"bolus":60.65,"temp_basal":12.2,"scheduled_basal":0.9},"current_target":126,"insulinForManualBolus":2.32,"manualBolusErrorString":0,"minDelta":2,"expectedDelta":-17.8,"threshold":4.7,"predBGs":{"IOB":[132,127,123,117,112,106,99,92,85,77,68,58,48,39],"ZT":[132,109,88,68,49,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39],"COB":[132,128,126,124,122,121,121,121,122,123,124,126,128,130,132,134,136,139,141,143,145,147,149,150,151,152,153,153,153,153,152,151,150,148,148,147,146,146,145],"UAM":[132,133,135,138,141,145,149,154,159,165,170,176,183,189,195,202,208,214,220,227,232,238,244,249,254,258,263,267,270,273,275,278,279,280,281,281,280,280,279,279,279,278,278,278,278,278,278,279]},"COB":39,"IOB":4.2,"BGI":-1.3,"deviation":8.3,"ISF":3.7,"target_bg":7,"reason":"Autosens ratio: 1.09, ISF: 4→3.7, COB: 39, Dev: 8.3, BGI: -1.3, CR: 9→8.2, Target: 7, minPredBG 7.8, minGuardBG 7.2, IOBpredBG 2.2, COBpredBG 8, UAMpredBG 15.5, TDD: 73.75 U, 82% Bolus 18% Basal, Dynamic ISF/CR: On/On, Sigmoid function, AF: 0.8, SMB Ratio: 1; Eventual BG 15.5 >= 7,  insulinReq 0.23; setting 60m low temp of 0U/h. Microbolusing 0.2U. ","units":0.2,"rate":0,"duration":60}

> 2023-10-29T13:53:35+0000 [ApsManager] APSManager.swift - enactBolus(units:automatic:) - 1282 - DEV: Bolus succeeded: 0.2

> 2023-10-29T13:53:36+0000 [DeviceManager] DeviceDataManager.swift - pumpManager(_:didUpdate:oldStatus:) - 328 - DEV: New pump status Bolus: inProgress(LoopKit.DoseEntry(type: LoopKit.DoseType.bolus, startDate: 2023-10-29 13:53:34 +0000, endDate: 2023-10-29 13:53:42 +0000, value: 0.2, unit: LoopKit.DoseUnit.units, deliveredUnits: nil, description: nil, insulinType: Optional(LoopKit.InsulinType.lyumjev), automatic: Optional(true), manuallyEntered: false, syncIdentifier: nil, isMutable: true, wasProgrammedByPumpUI: false, scheduledBasalRate: nil))


* Bolus 1.55u at 12:35, displayed as manual, supposedly automatic:

> 2023-10-29T12:35:34+0000 [OpenAPS] OpenAPS.swift - determineBasal(currentTemp:clock:) - 80 - DEV: SUGGESTED: {"temp":"absolute","bg":189,"tick":"+12","eventualBG":218,"insulinReq":1.58,"reservoir":38.9,"deliverAt":"2023-10-29T12:35:34.289Z","sensitivityRatio":1.8369447016747245,"TDD":76.3,"insulin":{"TDD":76.3,"bolus":62,"temp_basal":13.4,"scheduled_basal":0.9},"current_target":126,"insulinForManualBolus":2.35,"manualBolusErrorString":0,"minDelta":10,"expectedDelta":-7.1,"threshold":4.7,"predBGs":{"IOB":[189,191,191,188,183,176,168,158,146,134,120,105,88,73,58,44,39],"ZT":[189,173,156,138,120,102,83,66,48,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39],"COB":[189,192,194,196,196,195,195,194,193,192,191,190,189,189,188,188,189,189,190,191,193,195,197,199,201,203,205,207,210,212,214,216,217,219,220,222,223,224,224,224,225,224,224,223,221,220,219,218],"UAM":[189,198,206,211,216,220,223,225,226,228,228,229,229,229,229,228,228,227,226,225,224,223,221,219,217,215,212,209,206,203,199,194,190,185,181,178,174,171,169,166,164,162,160,158,157,156,154,153]},"COB":60,"IOB":11.19,"BGI":-0.9,"deviation":8.7,"ISF":2.2,"CR":4.9,"target_bg":7,"reason":"Autosens ratio: 1.84, ISF: 4→2.2, COB: 60, Dev: 8.7, BGI: -0.9, CR: 9→4.9, Target: 7, minPredBG 10.4, minGuardBG 9.5, IOBpredBG 2.2, COBpredBG 12.1, UAMpredBG 8.5, Total insulin: 76.3 U, 81% Bolus 19% Basal, Dynamic ISF/CR: On/On, Sigmoid function, AF: 0.8; Eventual BG 12.1 >= 7,  insulinReq 1.58; setting 60m low temp of 0U/h. Microbolusing 1.55U. ","units":1.55,"rate":0,"duration":60}

> 2023-10-29T12:35:38+0000 [ApsManager] APSManager.swift - enactBolus(units:automatic:) - 1259 - DEV: Bolus succeded: 1.55

> 2023-10-29T12:35:41+0000 [DeviceManager] DeviceDataManager.swift - pumpManager(_:didUpdate:oldStatus:) - 328 - DEV: New pump status Bolus: inProgress(LoopKit.DoseEntry(type: LoopKit.DoseType.bolus, startDate: 2023-10-29 12:35:38 +0000, endDate: 2023-10-29 12:36:40 +0000, value: 1.55, unit: LoopKit.DoseUnit.units, deliveredUnits: nil, description: nil, insulinType: Optional(LoopKit.InsulinType.lyumjev), automatic: Optional(true), manuallyEntered: false, syncIdentifier: nil, isMutable: true, wasProgrammedByPumpUI: false, scheduledBasalRate: nil))

* Bolus 2.15u at 12:30, displayed as manual, supposedly automatic:

> 2023-10-29T12:30:32+0000 [OpenAPS] OpenAPS.swift - determineBasal(currentTemp:clock:) - 80 - DEV: SUGGESTED: {"temp":"absolute","bg":177,"tick":"+10","eventualBG":297,"insulinReq":2.18,"reservoir":41.05,"deliverAt":"2023-10-29T12:30:32.781Z","sensitivityRatio":1.7419432013698732,"TDD":74.15,"insulin":{"TDD":74.15,"bolus":59.85,"temp_basal":13.4,"scheduled_basal":0.9},"current_target":126,"insulinForManualBolus":4.14,"manualBolusErrorString":0,"minDelta":6.06,"expectedDelta":-6.9,"threshold":4.7,"predBGs":{"IOB":[177,180,180,178,174,169,162,153,144,133,120,107,92,78,65,52,40,39],"ZT":[177,161,145,128,111,94,78,61,45,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39],"COB":[177,181,184,186,188,189,191,192,193,194,195,197,199,201,203,206,209,213,216,220,225,229,234,239,244,249,254,258,263,267,271,275,279,283,286,289,291,294,296,297,299,300,300,300,300,299,298,297],"UAM":[177,182,187,190,192,194,195,196,196,197,197,197,197,197,197,197,197,197,197,197,197,197,196,196,196,196,195,195,194,193,192,190,189,187,185,182,179,176,174,172,170,168,167,165,164,163,162,161]},"COB":66,"IOB":9.538,"BGI":-0.9,"deviation":7.3,"ISF":2.3,"CR":5.2,"target_bg":7,"reason":"Autosens ratio: 1.74, ISF: 4→2.3, COB: 66, Dev: 7.3, BGI: -0.9, CR: 9→5.2, Target: 7, minPredBG 12, minGuardBG 9.6, IOBpredBG 2.2, COBpredBG 16.5, UAMpredBG 8.9, Total insulin: 74.15 U, 81% Bolus 19% Basal, Dynamic ISF/CR: On/On, Sigmoid function, AF: 0.8; Eventual BG 16.5 >= 7,  insulinReq 2.18; setting 60m low temp of 0U/h. Microbolusing 2.15U. ","units":2.15,"rate":0,"duration":60}

> 2023-10-29T12:30:38+0000 [ApsManager] APSManager.swift - enactBolus(units:automatic:) - 1259 - DEV: Bolus succeded: 2.15

> 2023-10-29T12:30:39+0000 [DeviceManager] DeviceDataManager.swift - pumpManager(_:didUpdate:oldStatus:) - 328 - DEV: New pump status Bolus: inProgress(LoopKit.DoseEntry(type: LoopKit.DoseType.bolus, startDate: 2023-10-29 12:30:37 +0000, endDate: 2023-10-29 12:32:03 +0000, value: 2.15, unit: LoopKit.DoseUnit.units, deliveredUnits: nil, description: nil, insulinType: Optional(LoopKit.InsulinType.lyumjev), automatic: Optional(true), manuallyEntered: false, syncIdentifier: nil, isMutable: true, wasProgrammedByPumpUI: false, scheduledBasalRate: nil))

---

From the pump history: 

* SMB 13:53
> {
    "amount" : 0.2,
    "duration" : 0,
    "id" : "bed077793102c4e9baa2fa93e640f04b",
    "timestamp" : "2023-10-29T13:53:34.764Z",
    "isNonPumpInsulin" : false,
    "isSMB" : true,
    "_type" : "Bolus"
  },

* Bolus 12:35 
> {
    "timestamp" : "2023-10-29T12:35:38.096Z",
    "duration" : 1,
    "id" : "7c8d7a6b281692bafcadd8aa3c2176a9",
    "_type" : "Bolus",
    "amount" : 1.55
  }

* Bolus 12:30
> {
    "duration" : 1,
    "id" : "6274f6941981b534a3b729d51d2b72f0",
    "amount" : 2.15,
    "timestamp" : "2023-10-29T12:30:37.794Z",
    "_type" : "Bolus"
  },

What is very odd about your logs is that no bolus prior to `2023-10-29T13:53:34.764Z` shows the `isSMB` and `isNonPumpInsulin` properties. Moreover, there are no other boluses between 12:35 and 13:53, so it's hard to compare. 

@JohnKitching, can you please provide more information as to when you updated to latest `dev`, what version / commit of `dev` you were running before that and if you had any customizations in place that might alter respective parts of the `DataTable` module and the `PumpHistory` store and datatype?

**Comment by JohnKitching** [comment]
I updated to 2.2.6 today at approx 13:35
Previous version was 2.2.2 I think (I'm not certain because I think I did two builds of 2.2.2 and called the last one 2.2.3 which it wasn't). 
Not sure if it's relevant but we had a DST change last night and I synced the pump (Dash) time this morning but I'm not sure exactly when.

**Comment by dnzxy** [comment]
Okay, then I think this answers the weird glitch you saw in the view. With latest dev, we extended how PumpHistory entries are stored (there are new properties `isSMB` and `isNonPumpInsulin`*) and based on these properties for every pump history entry, the insulin treatments for bolus are displayed differently. 

If you updated at ~13:35, that explains why only boluses after that time show the new properties, hence why your history displays SMBs after that time as SMBs, and SMBs prior to that timestamp still as "Manual Bolus".

**Comment by dnzxy** [comment]
I just double-checked: The SMB flag `isSMB` was added with PR #219, that should be iAPS v2.2.5.

**Comment by dnzxy** [comment]
@Jon-b-m This issue can be closed / marked as solved.
