### ISSUE TITLE
FEATURE REQUEST: Profile Screen Insulin % Slider

### ISSUE THREAD

**Issue by EvanWhobrey** [Artificial-Pancreas/iAPS#291]
Hey, I'm not sure if this is in anyones capabilities, but as a user with zero code understanding, would be be possible to move the "insulin slider" below the percentage number so that you can see what you're adjusting easier? Currently when you reach above the number you need to either hold your finger on the slider and drag it down and then you can sew that you're doing. Hoping this is where we appropriately can ask this. Thanks in advance!

**Comment by Jon-b-m** [comment]
FIx is now in dev
