### ISSUE TITLE
[Bug] Enact Bolus has no sanity check

### ISSUE THREAD

**Issue by LiroyvH** [Artificial-Pancreas/iAPS#309]
The field to enter a bolus doesn't have a sanity check. Whilst it checks for a max bolus, it doesn't check for a minimum bolus nor does it respect the Bolus Increment. This means you can enter impossible values such as 0.0001U. This makes the app crash immediately after running FaceID. Moreover, for the 2nd issue, if your Bolus Increment is set to 0.5: you can still try to bolus 0.025 or, as another example, 1.025 - whilst neither ought to be possible with 0.5 increments.

Ideally, minimum bolus is tied to bolus increment. However, that's currently a setting within SMB options rather than a pump setting. Question is: how else do you determine the safe minimum the bolus calculator should accept? (0.1 is default  increment, which is compatible with all pumps, but if you have a pump that can do less: maybe you want to take advantage of that and manually give a smaller bolus too (especially when very insulin sensitive.)). Hence why I suggested moving this setting to the Pump Settings rather than keeping it under SMB-settings. (Or do both, with Pump Settings setting the absolute minimum SMB must respect too, if you want SMB to have different increments for some reason - but I don't think anybody will do that. (If anything, people probably sooner want to be able to set a different increment in the Watch-app; as with 0.025U bolus increment it takes aaaaaaaages to scroll or tap + for larger boluses.)). 

Either way, Enact Bolus shouldn't allow impossible values. :) 

-edit- Perhaps slightly related to https://github.com/Artificial-Pancreas/iAPS/issues/253 as well, which could also benefit from a more "global" bolus increment setting to ensure it's compatible with the pump. 
-edit- To add: using this with Medtronic.

**Comment by Jon-b-m** [comment]
Are you using main branch?
There is a sanity check done by LoopKit after tapping enact

**Comment by LiroyvH** [comment]
@Jon-b-m Running on dev with Medtronic. The app crashes upon tapping enact when entering a value such as 0,0001. Might be the handling of the sanity checks goes wrong.
