### ISSUE TITLE
Version 1.5 App closes when clicking on CGM in settings

### ISSUE THREAD

**Issue by CSlycord1** [Artificial-Pancreas/iAPS#31]
As title suggests ... I build app and began to set up app; i.e. Specifically CGM and pump.  CGM was set as Dexcom.  I tried to go back into CGM and the app closes out and returns back to home screen.  

iPhone 12 mini on iOS 16.4.1
iAPS build v1.5.0-1
Branch: Main 91fc8446
Dexcom 6G
Omnipod Dash pod

**Comment by avouspierre** [comment]
Thanks @CSlycord1 for this feedback. Could you give some detail ? 
- what do you mean by « go back in cgm » ? Which menu / screen ? 
- the issue always occurs and only once ? 

Thanks

**Comment by CSlycord1** [comment]
what do you mean by « go back in cgm » ? Which menu / screen ?
-- Going back into settings where you can assign a pod and CGM data.  I had already set up CGM data to pull from Dexcom and provided credentials.  This was my first build so I was going back into everything to double check settings, etc.... When trying to go back into CMG settings the app closes and goes back to the iphone homescreen.

the issue always occurs and only once ?  YES this is a reoccurring issue.  I have yet to be able to reaccess the CGM settings screen after the initial set up

**Comment by avouspierre** [comment]
OK. I close the issue.
