### ISSUE TITLE
Entering carbs on watch has got extremely slow

### ISSUE THREAD

**Issue by JohnKitching** [Artificial-Pancreas/iAPS#319]
iPhone 14 pro max with iOS 17.0.3
Apple watch ultra 1 with watchOS 10.1.1
iAPS 2.2.7 dev build 56dfcea

Entering the carbs is ok but the wait for confirmation sometimes takes nearly a minute. I'm not bolusing (or displaying the bolus option), just entering carbs.

**Comment by LiroyvH** [comment]
There any specific moment this happens or it always happens? I'm getting confirmation within two seconds, but I keep iOS and WatchOS (Series 9) up to date so running a bit different versions than you are.

**Comment by JohnKitching** [comment]
No, not always but often. 
I can't identify when it does and when it doesn't.
