### ISSUE TITLE
Add Future Carbs

### ISSUE THREAD

**Issue by andersonc1** [Artificial-Pancreas/iAPS#336]
I noticed we can no longer add carbs in the future which was very useful after high protein meals. I’d usually enter 10-15 carbs an hour or two into the future so iAPS would give extra insulin when the time came. Can we please have this back? It is simpler to me than entering FPU. Thank you.

**Comment by avouspierre** [comment]
Agree with this limitation to allow to add future carbs. Push a fix in dev.

**Comment by Jon-b-m** [comment]
It's in dev now!
