### ISSUE TITLE
Replace pod result in blocker: "no pod paired" error

### ISSUE THREAD

**Issue by LiroyvH** [Artificial-Pancreas/iAPS#34]
Hi,

When using the option to replace the Pod (Eros, not expired yet), it will get you to the Deactivate Pod screen as it should. After successfully deactivating the existing Pod, you're forwarded to the "Pair Pod" screen so you can setup a new Omnipod. This screen will, instead of looking for a new Omnipod, unfortunately keep saying "No pod paired". It shows a "Retry"-button, which doesn't work and it won't actually give any option to try and pair the pod. It won't look for a new pod either.

To fix it, you're forced to go back to the deactivate pod window and then back to the existing, now deactivated, omnipod. Then you can again choose "Replace pod", which will throw an error that the pump is deactivated and offers "Discard Pod". Once removed, you're again forwarded to "Pair Pod" and this time: it will actually try looking for the new Omnipod and you can actually properly link it.

![IMG_6940](https://user-images.githubusercontent.com/4643445/235452093-5fb807b0-f7c9-44d2-adc0-2b2de0f5fa07.PNG)

**Comment by avouspierre** [comment]
Hi @LiroyvH All these screens and functionalities are provided by the Loop components and iAPS doesn't change anything. Sometimes the connexion with the pod are not "stable". Which transmitter do you use (Orange Link, rileyLink ?) and what's the distance with all pod/transmitter/iphone ? 

Could you confirm the issue occurs for each pod or only occasionaly ?

**Comment by LiroyvH** [comment]
Ola @avouspierre, this has so far happened on each Pod using "Replace Pod". I'm using an OrangeLink, but I don't think it's a connection problem. Its always reproduceable. The steps are:
- Tap Settings-icon
- Tap Pump
- Tap the Omnipod
- Tap "Replace Pod". The app will now note that a pod is active and that you have to deactivate it first.
- Tap "Deactivate"
- **Pump beeps**, Omnipod is now deactivated. The app shows "Deactivated" with a blue checkmark.
- Tap "Continue".
- App now shows the "Paid Pod" screen with instructions like in the screenshot.
- Tap "Pair Pod"
- App will instantly throw an error "No pod paired" with a "Retry" button.
- Tap "Retry" will not do anything, it will just repeat there's no Pod Paired.
- Go back twice, back to the "Omnipod" screen. The pump still shows there, but says that Insulin Delivery is suspended.
- Tap "Replace Pod" again, which is still an option.
- The app once again shows the "Deactivate Pod" window.
- Tap "Deactivate pod". The app now immediately errors out and says there's No pod paired. It asks "Discard Pod" and "Retry".
- Select "Discard Pod"
- Confirm you really want to discard it.
- App now transports you to "Pair Pod" screen again.
- Tap "Pair Pod" 
- This time, the app doesn't instantly throw an error but actually starts looking for the new Omnipod.
Pair succesful! 

I made a video of it if it helps? Then you can see what happens if you want? I'll just have to upload it to YouTube or something. :) 

I don't think it's a connection issue, because a.) the existing Pod communicates with the OrangeLink instantly when de-activating, takes only a few seconds. b.) when you go back and try again: it will pair with the new pod just fine, c.) this happens *every time* that the "Replace Pod" feature is used whilst an active Omnipod is still connected. Deactivating the existing pod works fine, but then in the next step to pair a new pod it will *instantly* throw the "No pod paired" error and will continiously do that. Tapping retry you can see it won't even try looking for a new Pod, it will just refuse. But there's no other way to do this, because you really have to use the "Replace pod" feature. 

Hope this helps! :)

**Comment by avouspierre** [comment]
Hi @LiroyvH I finally found a little difference between the implementation of Pod eros and Pod BLE during the pairing. I don't have a access to a Eros Pod but could you check in the setting of your Eros Pod if you have a correct information in the Insulin Type (even iAPS don't use this info) ?  

![IMG_A940A1853DFE-1](https://github.com/Artificial-Pancreas/iAPS/assets/4339604/5d3fb97b-8836-4bb3-b4d8-9065d6da696f)

**Comment by LiroyvH** [comment]
@avouspierre I think so :) ![image](https://github.com/Artificial-Pancreas/iAPS/assets/4643445/6e2da5fd-7169-4e21-bc0c-395126c54700)

**Comment by avouspierre** [comment]
@LiroyvH OK. Could you try to change the code (to test) in the file Omnikit > OmniKit > PumpManager > OmnipodPumpManager > pairAndPrime(....) with commenting the current code and add a line ? 

`   public func pairAndPrime(completion: @escaping (PumpManagerResult<TimeInterval>) -> Void) {
        
//        guard let insulinType = insulinType else {
//            completion(.failure(.configuration(nil)))
//            return
//        }
        let insulinType = InsulinType.humalog
`

and try next pairing...

**Comment by avouspierre** [comment]
try to use the branch to test...hoping some the issue

 https://github.com/Artificial-Pancreas/iAPS/tree/dev-eros-issue

**Comment by avouspierre** [comment]
The correction done in the version available in current dev resolved this issue.

**Comment by francescaneri** [comment]
happened again. my daughter was not with me. i think its about the distance between pod and orangelink (in my case)

**Comment by francescaneri** [comment]
With the new dev (es. dev 6c701dd) the problem seems to have disappeared. who can test it. thanks

**Comment by LiroyvH** [comment]
I'd love to test it, but I'd have to ruin 2 pods. The pods are a major problem for me (leaking, no site absorption) so I'd effectively kill two of them. 

If nobody who actually uses Omnipod Eros can test it, then I'm happy to sacrifice them as this bug does need to be squashed completely - but otherwise I'd rather give them to someone who can actually use them. :P

**Comment by sethgagnon** [comment]
closing based on comments above

**Comment by LiroyvH** [comment]
@sethgagnon Hmmm I think it's premature to close this issue. This has not been tested first and foremost as discussed in the last comment above yours, but secondly: it appears, based on comments from @Jon-b-m on Discord, that this particular bug has not actually been addressed. :) Hence why it hasn't been tested either as that would ruin 2 pods for no reason. 

That wasn't posted here yet, but I think closure was already premature due to no changes having been tested.
Please reconsider reinstating the Open status. Thanks!

**Comment by Jon-b-m** [comment]
There's fix in dev for this, for a bug in the Omnipod simulator, but could probably we addressing bug in real pumps also. Please test it.

**Comment by francescaneri** [comment]
Unfortunately problem still encountered! 97a8cc3eeb7e87b2f43c469d42f6cae1f49f0281

**Comment by Jon-b-m** [comment]
That's unfortunate. This mysterious bug isn't sorted out in LoopKit yet, but I was hoping this recent fix from Joseph Moran might have fixed it to some extent.
