### ISSUE TITLE
Ignore trailing slash in NS URL

### ISSUE THREAD

**Issue by LiroyvH** [Artificial-Pancreas/iAPS#355]
When entering an URL for the nightscout server, if the user includes a trailing slash (eg https://night.scout/ instead of https://night.scout): this results in an error 404 as we start requesting https://night.scout//api instead of just /api. 

For convenience sake, iAPS should ignore the trailing slash if a user enters it.

**Comment by Jon-b-m** [comment]
OK. Will you PR this small fix?

**Comment by LiroyvH** [comment]
@Jon-b-m Yep I'm going to try!

**Comment by Jon-b-m** [comment]
Here's some help::
<img width="436" alt="image" src="https://github.com/Artificial-Pancreas/iAPS/assets/53905247/109dd327-e71e-43ed-89f8-098816ccbff1">

**Comment by LiroyvH** [comment]
Fixed! Thanks!
