### ISSUE TITLE
[enhancement] Refine `Settings / Watch` section

### ISSUE THREAD

**Issue by bashjs** [Artificial-Pancreas/iAPS#380]
## Description
- The setting `Display on Watch / Glucose Target` is incorrect since it shows the `Eventual Glucose` number on the Watch.
- While the word `Watch` in the Apple ecosystem clearly defines the Apple Watch device, we might want to change the menu item to include the `Garmin` word which will indicate the support of different Garmin devices (watches and bike computers).

## Screenshots
|Settings|Watch Configuration|Glucose Target|
|-|-|-
|![IMG_6298](https://github.com/Artificial-Pancreas/iAPS/assets/17122466/fc059ad8-82ca-4a86-80d0-173e60aad205)|![IMG_BA00B4509E61-1](https://github.com/Artificial-Pancreas/iAPS/assets/17122466/1c51dbaa-008d-4675-a888-afb19d3326ca)|![IMG_6299](https://github.com/Artificial-Pancreas/iAPS/assets/17122466/0b9724ec-d0c1-4e9d-9e81-9f908571db54)

## Proposal
- Change `Glucose Target` to `Eventual Glucose`
- Change `Settings / Watch` to `Settings / Watch and Garmin`
- Change `Watch Configuration` title to `Watch and Garmin`
- Change `Garmin Watch` section title to `Garmin Devices`

**Comment by bashjs** [comment]
I'll create a PR once a green light 🟢 is given to these changes. Any suggestions are welcome!

**Comment by Jon-b-m** [comment]
1.A change to Eventual Glucose, yes, is appropriate. 
2. Garmin is still a watch, right? I don’t think we need to complicate it more. 
4. Are there really other Garmin devices, except watches which iAPS is integrated with? If not, then keeping Garmin Watch seems reasonable to me.

**Comment by bashjs** [comment]
> 1.A change to Eventual Glucose, yes, is appropriate. 2. Garmin is still a watch, right? I don’t think we need to complicate it more. 4. Are there really other Garmin devices, except watches which iAPS is integrated with? If not, then keeping Garmin Watch seems reasonable to me.

When I'm cycling I use a Garmin bike computer which displays BG data via the same Data Field that is used on the watch.

**Comment by Jon-b-m** [comment]
I see. In that case your points are valid

**Comment by Jon-b-m** [comment]
Resolved in dev branch https://github.com/Artificial-Pancreas/iAPS/commit/c33d1e2756d9d2dad855e7c29d33ed17015bdf93
