### ISSUE TITLE
Give 2.2.8 the "latest" tag

### ISSUE THREAD

**Issue by hummelstrand** [Artificial-Pancreas/iAPS#387]
GitHub shows 2.2.7 as the "Latest" release. 
<img width="223" alt="image" src="https://github.com/Artificial-Pancreas/iAPS/assets/2979793/b3ae72e7-36bf-4c26-984f-fd3d37857420">

**Comment by Jon-b-m** [comment]
OK. Thanks. Will
Check

**Comment by Jon-b-m** [comment]
Fixed
