### ISSUE TITLE
Food entry for carbs shouldn’t save until confirmed 

### ISSUE THREAD

**Issue by Texbrackdelmonte** [Artificial-Pancreas/iAPS#392]
As a new IAPS user found an issue that should be resolved especially for those new 

when you click the food entry to add carbs the minute you enter those carbs it hits the loop cycle, you should be given an ok or confirm before it hits the cycle. If like me you hit the carb entry and then decide against it half way if you don’t go in and delete that phantom entry you evend up getting too much insulin. I know you can delete it but you should be asked to confirm or hit ok before it adds the entry in. Could be quite dangerous for a new user.

**Comment by dnzxy** [comment]
Are you using `main` or `dev`. In `dev` the behaviour around carb entry is essentially like you are describing it, unless I am misunderstanding how you are expecting the entry behaviour to work.

**Comment by debbyfurst** [comment]
I'm not the one who created this issue but I use Main and I agree that the carb entry should be confirmed before it appears. If that is coming in the next main release, issue resolved. Thanks!

**Comment by dnzxy** [comment]
Addressed in dev.
