### ISSUE TITLE
Live activity text is difficult to read over dark wallpaper in light mode

### ISSUE THREAD

**Issue by bstein** [Artificial-Pancreas/iAPS#403]
When you use a dark wallpaper and the system theme is dark, the text on the live activity notification is difficult to read.

A possible way to improve this might be to set the notification text color to white and the background color to black with ≈90% opacity. This should improve readability for this case while still ensuring readability over light wallpapers.

Dark mode                          |  Light mode
:-------------------------:|:-------------------------:
![](https://github.com/Artificial-Pancreas/iAPS/assets/6434784/8792ebb0-b66d-4784-ba4d-612fa73ea117)  |  ![](https://github.com/Artificial-Pancreas/iAPS/assets/6434784/36c8ed38-5c43-468f-b615-ee2522c6261e)

**Comment by dnzxy** [comment]
Fixed as of #397 - can be closed.
