### ISSUE TITLE
iAPS crashes when deleting Dexcom G6 CGM

### ISSUE THREAD

**Issue by jdtoppin** [Artificial-Pancreas/iAPS#418]
The app crashes when deleting a CGM to add a new transmitter. Log attached. Also shared the log through my phone when the crash occurred. On main 2.3.0.

[log.txt](https://github.com/Artificial-Pancreas/iAPS/files/13637451/log.txt)

**Comment by francescaneri** [comment]
Once the data of the new transmitter changed, in addition to the App Crash, I also found it difficult to resume the data from the sensor in iAPS. (at least 10/15 minutes pass and sometimes I have to re-enter the account to have blood sugar in iAPS) (dev E0488c2)

**Comment by Texbrackdelmonte** [comment]
I had the same issue as well, I could only get it to work by changing the pod. And re do it all. Glad it wasn’t just me

**Comment by Jon-b-m** [comment]
This has been fixed in dev already!
