### ISSUE TITLE
Added 7 day / weight average to statistics.json

### ISSUE THREAD

**Issue by scrappy** [Artificial-Pancreas/iAPS#42]
could you add 7 day average for TDD into statistics ... currently only past 24h is available, but like the longer time average to use for calculations ( ie. ISF = 100 / TDD ) ...

         "Insulin": {                             +
             "TDD": 82.75,                        +
             "bolus": 82.25,                      +
             "temp_basal": 0.5,                   +
             "scheduled_basal": 0                 +
         },                                       +

thx

**Comment by Jon-b-m** [comment]
Added

**Comment by Jon-b-m** [comment]
Fix in dev branch
