### ISSUE TITLE
Dev: no help info in Dynamic ISF menu items

### ISSUE THREAD

**Issue by SjpStanley** [Artificial-Pancreas/iAPS#423]
Title says it all.  V. 2.3.1 (12). Was there in (11) too

**Comment by Jon-b-m** [comment]
Yes, I'm aware. It's on my list, unless someone else will do it before me. It's rather trivial.

**Comment by Jon-b-m** [comment]
Now PR:ed to dev. To test, please check out the feature branch "descriptions_pop_up".

**Comment by Jon-b-m** [comment]
Now in dev branch!
