### ISSUE TITLE
NS reports total daily carbs are not rounded 

### ISSUE THREAD

**Issue by paddingtonil** [Artificial-Pancreas/iAPS#433]
DEV build fc8126d and earlier NS generates reports where daily cabs are hexdecimal like 99.80000000000001

**Comment by tredair7** [comment]
I see the same thing in Main

![IMG_1120](https://github.com/Artificial-Pancreas/iAPS/assets/55993777/10ec3d93-78a8-4405-b54b-479799cff7ff)

**Comment by Jon-b-m** [comment]
Isn't this a NS issue? Please report it in in NS repo, here:
https://github.com/nightscout/cgm-remote-monitor
