### ISSUE TITLE
Show / hide prediction lines

### ISSUE THREAD

**Issue by holmfirth** [Artificial-Pancreas/iAPS#437]
Would it be possible to toggle the ZT and IOB lines off and on via a switch, and have the UAM line only show if UAM is detected?

**Comment by Jon-b-m** [comment]
In dev branch you can toggle these off/on by a tap. 

The UAM prediction is only displayed when enabled in SMB settings.

**Comment by holmfirth** [comment]
> In dev branch you can toggle these off/on by a tap.
> 
> The UAM prediction is only displayed when enabled in SMB settings.

ahhhh thank you - I use Dev, where do I toggle them please?

**Comment by Jon-b-m** [comment]
Home View. Main Chart. Tap the chart once to toggle

**Comment by Jon-b-m** [comment]
Ah, wait. Sorry I thought you meant the legend.

**Comment by holmfirth** [comment]
ahhhh, not the icons at the bottom, I want to hide the lines themselves...

**Comment by Jon-b-m** [comment]
The predictions will be displayed when "active". You can't toggle these off

**Comment by holmfirth** [comment]
OK cheers. Shame as ZT and IOB are ones I doubt I'd ever need to see.
