### ISSUE TITLE
Data sent to Garmin Device

### ISSUE THREAD

**Issue by gonkowonko** [Artificial-Pancreas/iAPS#447]
I believe the data being sent to the Garmin Device has changed in the dev branch, which has led to a breakage in what is shown on a garmin device. 

Previously one of the properties was "**trendRaw**" but it used the text description i.e "**FortyFiveDown**" or "**DoubleUp**", now it appears that the data sent uses the special characters →, ⇈.  See this link for how its used [Link to GarminWatch repo](https://github.com/Artificial-Pancreas/garminWatch/blob/01735f7dcef7877a60fb0e740b9d028725160bb4/iAPSGarminDataField/source/iAPSDataFieldView.mc#L229)

Another useful property was "**glucoseDateInterval**" which is similar to "lastLoopDateInterval" which is no longer be sent across. This was useful for when showing the time when the BG value was last updated if looping has been disabled due to something like a manual basal being set.

It would be nice if these 2 properties could be reinstated back if possible.

**Comment by Jon-b-m** [comment]
I don't use the Garmin myself. Please PR, if needed.

**Comment by gonkowonko** [comment]
What does that mean? If all users want to continue to use the garmin functionality one of us need to fix it?

**Comment by gonkowonko** [comment]
I've done some hacks to see if they work will test throughout the next few days if it works, I'll refine and create a PR 👍

**Comment by gonkowonko** [comment]
PR Raised https://github.com/Artificial-Pancreas/iAPS/pull/470
