### ISSUE TITLE
Feature Request: Timed Profiles

### ISSUE THREAD

**Issue by hmaitken** [Artificial-Pancreas/iAPS#460]
I’d love to be able to set a profile to action at a specific time. Use case: I need a bit more insulin just before I wake up to counter feet on the floor. I’d like to be able to set a profile to activate 30-60 mins before my alarm goes off/waking time. This is to counter variable waking times. Many thanks!

**Comment by smilodonis** [comment]
You could achieve this via middleware today.

**Comment by Jon-b-m** [comment]
You can achieve this with the the iOS automations now. It’s in all public  iAPS branches
