### ISSUE TITLE
iAPS crashes every loop cycle

### ISSUE THREAD

**Issue by MikePlante1** [Artificial-Pancreas/iAPS#466]
My Eros pod expired at 80hrs and I put a new pod on. But since then, iAPS kept crashing as soon as a bolus was sent, though the pod would still deliver the entire bolus. Also, if I triggered any of the diagnostics commands in the pod manager it would often crash, but sometimes the command worked fine.

I'd been running the latest dev (I absolutely love that dynamic island feature) all day and it's been working wonderfully until I changed my pod. I then switched to a different version of dev, but the problem kept happening. I then switched to main 2.2.8 and no more crashing, switched back to the latest dev again and still no more crashing.

When I hooked it up to Xcode, the log would say Terminating app due to uncaught exception 'NSInvalidArgumentException' I copied the console output into a text file and attached it as well as the log exported from the app.

[log_prev.txt](https://github.com/Artificial-Pancreas/iAPS/files/13866118/log_prev.txt)
[Xcode_log.rtf.txt](https://github.com/Artificial-Pancreas/iAPS/files/13866129/Xcode_log.rtf.txt)

@itsmojo commented this on Discord: `The Xcode log indicates this crash is some HealthKit issue when trying to store a bolus. This stuff has been getting working on recently. If it’s still happening with the latest code, I’d suggest turning off Apple Health in iAPS until @Jon Björn says to try it again.`

**Comment by MikePlante1** [comment]
I posted to Discord when this happened on November 29th, but didn't think to add it here. Better late than never.

**Comment by Jon-b-m** [comment]
There a testing branch now with several Health Store fixes. In a PR to alpha. Please check this out.

**Comment by Jon-b-m** [comment]
I was able to reproduce this bug. E this or indicated format of entry sent to Health Store wasn't appropriate. Interestingly when converting ID to NSString the fatal error disappeared. Coincidence or a real fix?

**Comment by Jon-b-m** [comment]
Fix now in main and sev
