### ISSUE TITLE
Automatic SMBs while SMBs disabled profile is enacted

### ISSUE THREAD

**Issue by snickerdoodleparent** [Artificial-Pancreas/iAPS#477]
On Main 2.3.3 (Xcode build) with an iPhone SE. 
![0](https://github.com/Artificial-Pancreas/iAPS/assets/99215346/59b2b663-968b-434f-989e-757ea29be0c6)

Made a brand new override profile: SMB disabled from 21:00 - 6:00 and enacted it around 9pm.
![1](https://github.com/Artificial-Pancreas/iAPS/assets/99215346/5d0b4959-3dfe-4e60-9c90-79142f51a501)
![2](https://github.com/Artificial-Pancreas/iAPS/assets/99215346/9d62afb4-6b42-462d-afdb-fd026b620557)
![3](https://github.com/Artificial-Pancreas/iAPS/assets/99215346/d252a699-91b6-45b7-bb96-64eb43a0a3cc)

Saw 2 SMB go in automatically at 9:30pm & 9:55pm
![NS-10pm](https://github.com/Artificial-Pancreas/iAPS/assets/99215346/8078da49-8281-48a6-9ee6-556fce99bef4)

Not sure if it would be helpful to see the OpenAPS pill at those times:
![OpenAPS930](https://github.com/Artificial-Pancreas/iAPS/assets/99215346/f8ac8c55-35db-424e-ab3e-0176749c34ee)
![OpenAPS955](https://github.com/Artificial-Pancreas/iAPS/assets/99215346/519337dd-45c7-488c-ae52-0cd1adbd64d0)

Log files:
[log 2.txt](https://github.com/Artificial-Pancreas/iAPS/files/13923815/log.2.txt)
[log_prev 2.txt](https://github.com/Artificial-Pancreas/iAPS/files/13923816/log_prev.2.txt)

**Comment by Jon-b-m** [comment]
I have made a testing branch, refactoring this feature. It's "main_smb_recfactoring" if you want to test.

https://github.com/Artificial-Pancreas/iAPS/tree/main_smb_recfactoring

**Comment by snickerdoodleparent** [comment]
I tested this and it seems this is working. I never saw SMB the first hour they were scheduled to be off, or remainder of time. Thanks!
