### ISSUE TITLE
Insulin delivery not disabled despite bg below 65 (3.6mmols/dL)

### ISSUE THREAD

**Issue by JELCRAWFORD** [Artificial-Pancreas/iAPS#484]
We have observed insulin delivery continuing via high basal delivery (above programmed) if iAPS has a prediction of high BG even if current BG is below 65/3.6.  This problem is amplified in very low BG situations as are evident in the logs, where BG was below 48 but high temp basals were being delivered.
[crawford_log_prev.txt](https://github.com/Artificial-Pancreas/iAPS/files/13983446/crawford_log_prev.txt)
[crawford_log.txt](https://github.com/Artificial-Pancreas/iAPS/files/13983448/crawford_log.txt)

**Comment by Jon-b-m** [comment]
A timestamp would help a lot when going through the logs, please 🙏🏻.

**Comment by Jon-b-m** [comment]
I've answered in Discord regarding this issue. The OpenAPS code isn't always suspending temp basal insulin when under threshold by design.
