### ISSUE TITLE
Random iAPS stoppage overnight

### ISSUE THREAD

**Issue by sommerfami** [Artificial-Pancreas/iAPS#510]
IAPS has been shutting down randomly overnight and is stalled when opening in the morning. This has happened at least 4 times. I have screenshots and logs for two of the events which are attached. Upon waking I check iAPS first thing. It will be stalled with a Red Loop for greater than 300min and will not automatically reconnect. Function only regained after forcing communication with Dash through Test Beeps. I have been using iAPS since Nov 23. Previously Looped for 5 years and never had this happen. Dexcom G6 used in both Loop and iAPS. Same iphone 13 running iOS 17.2.1. iAPS ver 3.3.1? (sorry already deleted app. Build was 1-9-24). 
[iAPS log.txt](https://github.com/Artificial-Pancreas/iAPS/files/14215261/iAPS.log.txt)
[iAPS log02062024.txt](https://github.com/Artificial-Pancreas/iAPS/files/14215262/iAPS.log02062024.txt)
[log_prev.txt](https://github.com/Artificial-Pancreas/iAPS/files/14215263/log_prev.txt)
[log.txt](https://github.com/Artificial-Pancreas/iAPS/files/14215264/log.txt)
![IMG_0950](https://github.com/Artificial-Pancreas/iAPS/assets/49995292/f4fda095-0620-4b45-9b11-132722571e14)
![IMG_0949](https://github.com/Artificial-Pancreas/iAPS/assets/49995292/eb26d78f-3401-4a98-8638-5253db38017d)
![IMG_0948](https://github.com/Artificial-Pancreas/iAPS/assets/49995292/13940539-521b-48bb-873b-9d22520ef2c5)
![IMG_0944](https://github.com/Artificial-Pancreas/iAPS/assets/49995292/9fc782d6-977f-42d7-a028-a3be577770d5)
![IMG_0943](https://github.com/Artificial-Pancreas/iAPS/assets/49995292/c82128bb-6a35-410d-a326-db002e955a85)
![IMG_0942](https://github.com/Artificial-Pancreas/iAPS/assets/49995292/2b6c85e2-f5d7-422d-9b41-18fdd91761a9)
![IMG_0941](https://github.com/Artificial-Pancreas/iAPS/assets/49995292/ae7f36b5-5e1e-43b6-bf12-2f631c6a5f84)
![IMG_0934](https://github.com/Artificial-Pancreas/iAPS/assets/49995292/eebac210-a014-40ed-aac0-9a47c5e56a6b)
![IMG_0933](https://github.com/Artificial-Pancreas/iAPS/assets/49995292/1980ac20-6cff-437a-b3ad-1aaa2038ff5f)
![IMG_0932](https://github.com/Artificial-Pancreas/iAPS/assets/49995292/666d13ef-a874-4e1e-9a8e-8331f21be29e)
![IMG_0923](https://github.com/Artificial-Pancreas/iAPS/assets/49995292/d3dd9154-b91f-4139-9616-a578bf3e0825)
![IMG_0922](https://github.com/Artificial-Pancreas/iAPS/assets/49995292/0c04c24f-d94c-42f7-93c2-b1102fe4bc24)
![IMG_0921](https://github.com/Artificial-Pancreas/iAPS/assets/49995292/1659d639-8353-4db7-883f-055cdf47d442)

**Comment by sommerfami** [comment]
I am not a developer but a simple user. @dnzyx (Dan Moody) suggested I post shots and logs here after reviewing. I am not good at this and I apologize for breaking any protocols or if some info is irrelevant (seems like some of the screenshots may not be related). The dates of the incidents were 2-6-24 and 1-14-24 which have both shots and logs. Your help is greatly appreciated. I have moved back to Loop temporarily until the source of these shutdowns can be determined.

**Comment by Jon-b-m** [comment]
Upon first look it looks like a CGM problem, as CGM readings are missing. Without a new fresh CGM reading iAPS will not loop . Is your transmitter getting old?

**Comment by sommerfami** [comment]
The transmitter had a month left on it at the time. I had been using Loop for 4 years without any connectivity issues like this. Been using iAPS for about a month when problems started creeping in. It is NOT a Dexcom problem. Been using that for about 10 years. Please read the logs if possible. I moved back to Loop because this is so disturbing. I saw another apparent case on FB and recommended submitting logs. I think this problem is out there and no one is reporting it because they get the same answer. It's Dexcom. No, it is iAPS when used with Dexcom.

**Comment by Jon-b-m** [comment]
Your screenshot for Dexcom app shows missed readings for 3-4 hours. IAPS can’t get its readings from listening at the Dexcom traffic. If no traffic(as your screenshot illustrates), no readings in iAPS.
