### ISSUE TITLE
App Icon not updating 

### ISSUE THREAD

**Issue by kylmcw** [Artificial-Pancreas/iAPS#518]
The app icon is not changing.

it has previously worked, and no updates have been applied since.

I changed to the circular icon attached, and now it won’t change to anything else. Previously it worked for any combination or sequence of icon selection.

attached logs.
[log.txt](https://github.com/Artificial-Pancreas/iAPS/files/14228471/log.txt)

![IMG_0788](https://github.com/Artificial-Pancreas/iAPS/assets/156543991/7aad7990-f674-44fb-9e3d-37b534fc9f62)
![IMG_0789](https://github.com/Artificial-Pancreas/iAPS/assets/156543991/27331859-7747-4334-9cfc-ac5127c91bcf)

**Comment by Jon-b-m** [comment]
Which iOS are you currently running? can I see your iAPS fork also, please, provided you have one?

**Comment by kylmcw** [comment]
17.3.1
Running 2.3.3, it did update eventually, maybe I was just impatient, but it took a while and a few app restarts (not sure this did anything however). Do you still need my fork? I don't have any custom middleware or anything.
