### ISSUE TITLE
Feature request: Hide meal button

### ISSUE THREAD

**Issue by straykatz** [Artificial-Pancreas/iAPS#523]
First of all - very nice updates in Version 3!! 

Second - I had a minute of worry last night, when I did not have a temp target button anymore ... TTs are my main control mechanism. Then I found the toggle to turn it on.

Brings me to the feature request:

Please also add a **toggle for the meals button** in the settings, so it can be hidden from the main display. 

Reason: I never use meals - I only ever use TTs, sometimes "Profiles", and rarely "Add Insulin". Hiding the button would make the interface less crowded.  

I assume for other people who are using iAPS as an almost fully closed loop, announcing meals  is also the first entry to drop. 

Not exactly urgent, more a "nice to have".  ❤️

Thank you! 

![image](https://github.com/Artificial-Pancreas/iAPS/assets/45725845/0feec6a7-c46e-43b9-a444-df6fc64d9c46)

![image](https://github.com/Artificial-Pancreas/iAPS/assets/45725845/4797db96-e984-4a3b-8289-f5677735cf6c)

**Comment by Jon-b-m** [comment]
I guess so.

**Comment by Jon-b-m** [comment]
Since this is a simple change to do yourself and since nobody else has been requesting this before, I think it makes more sense to leave this modification to you.

**Comment by straykatz** [comment]
OK :-)
