### ISSUE TITLE
Feature request : adding Dexcom One+ as CGM

### ISSUE THREAD

**Issue by chmloop** [Artificial-Pancreas/iAPS#524]
according to Marion Baker on discord in the cgm Dexcom section (https://discord.com/channels/1120154740857245808/1124371511105572936/1206243313238286356): 
A user on zulipchat modified the search prefix string for One+ and is using it with Loop. Searched for DX02xx. For G7 the search is DXCMxx.

**Comment by chmloop** [comment]
testing it in real life ...

**Comment by chmloop** [comment]
see #530

**Comment by Jon-b-m** [comment]
It's in dev now.
