### ISSUE TITLE
Omnipod Dash: possibility to bolus continues after reservoir is empty

### ISSUE THREAD

**Issue by slaarhuis** [Artificial-Pancreas/iAPS#529]
I can bolus as much as I want when the indicator of the units left is on 0. I do get a warning when I'm below 10, but after that it keeps bolusing. I guess that should not be the case.

**Comment by slaarhuis** [comment]
Happens on 3.0.1 but also on earlier versions

**Comment by Jon-b-m** [comment]
It’s as expected, as there is a buffer. When completely empty the pod will start screaming.

**Comment by slaarhuis** [comment]
Thx Jon! Will it also scream if the pump sounds are silenced? I did hear
the < 10 U sound, but I was able to keep dosing more than 10 units after
that.

Thanks (for all the great work!),
Stephan

Op di 13 feb 2024 om 22:43 schreef Jon B Mårtensson <
***@***.***>

**Comment by Jon-b-m** [comment]
Yes. You can’t turn off the screaming.
