### ISSUE TITLE
FEATURE REQUEST: Add Start Time / Day to Profile

### ISSUE THREAD

**Issue by scrappy** [Artificial-Pancreas/iAPS#531]
not sure how to mark as a feature request vs bug ...

From a patient:

I also prefer TTs for exercise because I can schedule them for a future time. E.g. today I know I’m going for a run with family at 1130, so I schedule my TT to enact at 1030. I just did this now so that I don’t have to pull my phone out while driving to meet family (I’m also likely to forget by then).

Definitely great for anyone that has training classes ( ie. martial arts, gymnastics, etc ) where its always the same time ... maybe have it so that you can stipulate day of week ( not date ) so that its easy to be recurring: "Every Monday @ 5 pm" ...

**Comment by dsnallfot** [comment]
One way to implement this could be to add enacting/cancelling profiles to Siri Shortcuts (such as the carbs and temp targets that are available today). 

Shortcuts can be scheduled and/or location based (and run automatically without needing to be manually confirmed if they are triggered by a "focus"-mode that is set up to be triggered by a specific location)

**Comment by Jon-b-m** [comment]
Yes. Shortcuts can now be used for this purpose. Will land in dev shortly. It’s now in the “override_shortcuts” branch

**Comment by Jon-b-m** [comment]
This feature has been in main branch in form of shortcuts for a while now. I guess we can close this as completed?
