### ISSUE TITLE
v3.0.1 App crash on pump screen; 

### ISSUE THREAD

**Issue by CSlycord1** [Artificial-Pancreas/iAPS#541]
Formal log of issue based on: https://discord.com/channels/1120154740857245808/1123067925746700379

Was able to get to "pair pod" screen... then app crashes,  once you go back into pump screen it shows ready for canula insertion.  Cant get back to prime pod.  Pod wont insert as its not primed/ connected to iAPS.

App is crashing continuously when on pump screen.  Sometimes immediately other times after 3-4-5 seconds.

Iphone 15, iOS 17.2.1, Ominpod Dash, Dexcom G6, V3.0.1

Exported logs if they are useful -- unclear if they would contain any private/ personal information that I should wipe before I upload.

**Comment by CSlycord1** [comment]
I am late to the party here.. I think this issue can be deleted.  I now see the discussion on #Dash  channel.

https://discord.com/channels/1120154740857245808/1124371739544125522/1207347237135327262

**Comment by Jon-b-m** [comment]
Fix in main 3.0.2 and in dev
