### ISSUE TITLE
Feature Request: Auto-Rotate On/Off Toggle in UI/UX

### ISSUE THREAD

**Issue by ABloodyDiabetic** [Artificial-Pancreas/iAPS#545]
Add an auto-rotate on off toggle under UI/UX. I find auto rotate for screen rotation annoying (every time I pull my phone out of my pocket the screen orientation is upside down until I tilt my screen up), but I imagine some people like it for niche use cases, thus the toggle option would likely be most ideal.

**Comment by Jon-b-m** [comment]
You can prevent rotation in iOS control panel.
