### ISSUE TITLE
Feature request: warning notification if pump time is different than phone time (ie traveling)

### ISSUE THREAD

**Issue by treschny** [Artificial-Pancreas/iAPS#552]
This type of warning is already shown in pump settings, but can be easily missed when traveling and changing time zones

**Comment by Jon-b-m** [comment]
Will add this. It's on my list.

**Comment by treschny** [comment]
Thanks, Jon!Trent Reschny306.591.5299On Feb 26, 2024, at 7:24 AM, Jon B Mårtensson ***@***.***> wrote:﻿
Will add this. It's on my list.

**Comment by Jon-b-m** [comment]
It's now in a testing branch, "podState". Will soon land in dev.

**Comment by Jon-b-m** [comment]
in dev now

**Comment by treschny** [comment]
Thanks a bunch, JonTrent Reschny306.591.5299On Mar 2, 2024, at 6:44 PM, Jon B Mårtensson ***@***.***> wrote:﻿
in dev now
