### ISSUE TITLE
Delay in minutes cannot be changed in Coversion Settings

### ISSUE THREAD

**Issue by danisantaella** [Artificial-Pancreas/iAPS#590]
The issue is self descriptive. 

Once I try to change the default value from 60 minutes in the FPU, “save it” and then 60’ value can be found again. 

![IMG_8302](https://github.com/Artificial-Pancreas/iAPS/assets/23196604/1f0a2912-e9b1-4aab-b54a-f4ad2047098e)
![IMG_8301](https://github.com/Artificial-Pancreas/iAPS/assets/23196604/8b5d9388-b13f-4c6d-bb11-f5438e2fd190)

**Comment by Jon-b-m** [comment]
Minimum delay is 60 minutes. Maximum is 120 min.

**Comment by Merkaffe** [comment]
Fixed in dev. Now you can make adjustments

**Comment by Jon-b-m** [comment]
In dev you now can make bigger adjustments

**Comment by danisantaella** [comment]
Big thanks!!
