### ISSUE TITLE
Restrict CHO Input (250 cho)

### ISSUE THREAD

**Issue by francescaneri** [Artificial-Pancreas/iAPS#593]
This weekend it happened that my daughter mistyped the input of the cho and wrote instead of 10 cho, 1000 cho, and instead of 40 cho, 400 cho. Is it possible to put a warning (which you can set) so that it warns you that you are entering the wrong ones before you make the bolus? Thank you as usual for the work done

**Comment by Jon-b-m** [comment]
Yes, but at what amount? Currently there already is a max amount in pump settings: "Max Carbs". Then there is another "Max COB" in OpenAPS settings.

**Comment by francescaneri** [comment]
okay! pump settings: "Max Carbs" I thought was daily. excuse. Close issue! thanks
