### ISSUE TITLE
ResistanceLowersTarget does not work

### ISSUE THREAD

**Issue by mountrcg** [Artificial-Pancreas/iAPS#645]
**Describe the bug**
due to this [line](https://github.com/Artificial-Pancreas/iAPS/blob/6383f62f11911a19a3abe1e22268d3704b101174/FreeAPS/Sources/Models/Preferences.swift#L70) the oref functionality `resistance_lowers_target` does not work as it is always `false`

**To Reproduce**
1. activate that setting in preferences
2. watch for an autosens >1
3. see if target in popup will be lower when from from profile
4. See that is the same, which would be an error and target is not adjusted due to the setting in oref

**Expected behavior**
target need to be lower than profile target

**Solution**
`case resistanceLowersTarget = "resistance_lowers_target"` in preferences.swift (see above)

**Comment by Jon-b-m** [comment]
Yes, I'm aware of this. However, your suggested fix will reset the OpenAPS settings for everyone. 
There is another fix to migrate this conversion without resetting which I'll push later

**Comment by Jon-b-m** [comment]
I pushed a fix to dev now.
