### ISSUE TITLE
Force update statistics / preferences

### ISSUE THREAD

**Issue by scrappy** [Artificial-Pancreas/iAPS#71]
During normal operations, updating said once a day isn't a problem, but it would be nice if at the bottom of the 'Statistics' Settings screen, there was a button for "Refresh uploaded data", or something like that ... not even really looking for statistics to be updated, but the ability to refresh preferences after changes are made to it

Our office does virtual appointments, and being able to have a patient make changes and have those changes instantly ( even with a press of a button ) update the online values would save a lot of "and now share your preferences.json file"

Thx

**Comment by Jon-b-m** [comment]
The preferences shouldn't ideally be mixed up with the optional statistics.json upload. Would be much better if the preferences.json was uploaded to NS only when/if changed. A PR making this happen would be accepted.

**Comment by Jon-b-m** [comment]
fixed in dev
