### ISSUE TITLE
Cannot set a BG target of 6.1, silent reset to 4 mmol/l

### ISSUE THREAD

**Issue by widmann** [Artificial-Pancreas/iAPS#712]
If I try to set a BG target of 6.1 mmol/l in the UI, the setting is silently reset to 4 mmol/l after saving and exiting the UI. Setting 6.0 or 6.2 mmol/l works, so there is a workaround. However, since there is no visual feedback of the reset and a target of 4 mmol/l could have serious side effects, I would consider this a high priority issue.

Steps to reproduce:
* Open the target BG UI.
* Set a target of 6.1 mmol/l.
* Press save.
* Go back to Settings.
* Re-enter the target BG UI and find the target set to 4 mmol/l.

Expected result:
* BG target set to 6.1 mmol/l.

Actual result:
* BG target set to 4 mmol/l.

A prerequisite is probably setting the BG units to mmol/l in the OpenAPS settings, but I have not systematically tested this yet.

I can provide screenshots if needed.

Version 4.3.0, Branch Dana BB1078B, German UI.

**Comment by Jon-b-m** [comment]
> If I try to set a BG target of 6.1 mmol/l in the UI, the setting is silently reset to 4 mmol/l after saving and exiting the UI. Setting 6.0 or 6.2 mmol/l works, so there is a workaround. However, since there is no visual feedback of the reset and a target of 4 mmol/l could have serious side effects, I would consider this a high priority issue.
> 
> Steps to reproduce:
> 
> * Open the target BG UI.
> * Set a target of 6.1 mmol/l.
> * Press save.
> * Go back to Settings.
> * Re-enter the target BG UI and find the target set to 4 mmol/l.
> 
> Expected result:
> 
> * BG target set to 6.1 mmol/l.
> 
> Actual result:
> 
> * BG target set to 4 mmol/l.
> 
> A prerequisite is probably setting the BG units to mmol/l in the OpenAPS settings, but I have not systematically tested this yet.
> 
> I can provide screenshots if needed.
> 
> Version 4.3.0, Branch Dana BB1078B, German UI.

Please test the PR:ed fix. https://github.com/Artificial-Pancreas/iAPS/pull/715
