### ISSUE TITLE
Sharing -> Date of Birth

### ISSUE THREAD

**Issue by scrappy** [Artificial-Pancreas/iAPS#713]
Date format saved appears to be skewed by timestamp ... not sure how to fix this one, but, for example:

This is what is in statistics.json for one user ( discord Typ1er )

`1982-09-30T23:00:00.000Z`

What he sees in the app is Oct 1st, 1982 ( which is correct ), but he's *west* of Zulu, so add +1 hr to that time and it 1982-01-10 ...

I need the date "as entered" vs "adjusted for timezone" ... we just need the date component, not the T* that is at the end ...

**Comment by Jon-b-m** [comment]
@scrappy Would you mind testing this:
formatter.timeZone = TimeZone(secondsFromGMT: 0)
