### ISSUE TITLE
Feature Request: Add post oref0 layer (to set the basal rate manually)

### ISSUE THREAD

**Issue by smilodonis** [Artificial-Pancreas/iAPS#743]
Hi Jon,

I would like to ask you to add a post oref0 layer to middleware.

I would like to change / set the basal rate manually in middleware code.

Example:
If (condition is TRUE){
set basal rate at 0.5U/h
}

Thank you. (we discussed this on Discord #Middleware on Jun 24)

**Comment by Merkaffe** [comment]
And if Oref wants to give SMB or suspend insulin? Do you mean to use this only in Open Loop mode? To me this would only be useful (perhaps) in open loop.

**Comment by smilodonis** [comment]
> And if Oref wants to give SMB or suspend insulin? Do you mean to use this only in Open Loop mode? To me this would only be useful (perhaps) in open loop.

While using this, SMB will be suspended. This is needed for activity like bikeride. Where SMB is completely off and basal rate is set by the current BG.

I would manually suspend basal if needed via middleware. Something like this below:

`if (enable_sportMode == true) {
   sportModeStatus = "ACTIVE";
   if (currentBG >= 12) {
      newBasal = 0.3;
   } else if (currentBG < 12 && currentBG >= 10) {
      newBasal = 0.2;
   } else if (currentBG < 10 && currentBG >= 9) {
      newBasal = 0.1;    
   } else if (currentBG < 9 && currentBG >= 4) {
      newBasal = 0;
   }`

**Comment by Jon-b-m** [comment]
PR:ed to dev branch
