### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by darrelld3** [Artificial-Pancreas/iAPS#751]
Add the Fatty Meal calculations checkbox when using the Bolus Calculator Eventual Glucose option![image](https://github.com/Artificial-Pancreas/iAPS/assets/69735322/725e729b-165b-466d-9cb9-f0deb388adcd![CD3EDC82-0C70-4DBD-989D-CA055C61F7FE_1_105_c](https://github.com/Artificial-Pancreas/iAPS/assets/69735322/cc42ad81-2c91-4630-94bb-f3e0d75a294d)

**Comment by Jon-b-m** [comment]
PR:ed to dev branch
