### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by darrelld3** [Artificial-Pancreas/iAPS#762]
Add basal setting to profiles. This would allow experimentation with different basal settings.

**Comment by smilodonis** [comment]
This is somehow already implemented. You can set up basal profiles in the middleware and call the profiles from there. (Check Middleware channel on Discord)

**Comment by darrelld3** [comment]
> This is somewhat already implemented. You can set up basal profiles in the middleware and call the profiles from there. Thats great but I don't see a new user coming from another system trying to figure out basals using middleware, do you? Most other options are already in profiles.

**Comment by Jon-b-m** [comment]
This is now implemented in new configuration profiles. Please test to see if it works for you? It’s currently in an open PR.

**Comment by darrelld3** [comment]
> This is now implemented in new configuration profiles. Please test to see if it works for you? It’s currently in an open PR. Otherwise you can already indirectly change the basal profile with the overrides. I think we talk about this in Discord, right?

Thanks, yes we did discuss this. I will install now.

**Comment by Jon-b-m** [comment]
Should I close this request as you already can change the basals with a normal override (with or without also changing the ISF/CR)?

**Comment by darrelld3** [comment]
Yes you can close this.
