### ISSUE TITLE
Safety request: max. bolus size guardrail

### ISSUE THREAD

**Issue by robinwo** [Artificial-Pancreas/iAPS#779]
When giving a manual bolus, I sometimes miss the “,” in my entry, resulting in a 10u bolus rather than 1,0. I once accidentally started bolusing 70 units because of that reason.

Before when using Loop, I was able to set a max. bolus size setting to prevent this from happening. Could we add this same safety guardrail into iAPS?

**Comment by smilodonis** [comment]
This is already implemented in iAPS. Settings->Pump Settings->Max Bolus . Set this to your maximum bolus setting. (Example given from iAPS version 4.5.0)

**Comment by robinwo** [comment]
Weird I’ve set this to 10 but it still allows for starting a 70u bolus. 

Is that by design or a bug? Or will it automatically stop the bolus when it reaches 10? (Bolus history does show 70u got accepted).

Expected behavior is to not allow starting a bolus exceeding this threshold.

**Comment by smilodonis** [comment]
I would update to the latest main version. If I'm not mistaken 2.3.3 had some bugs. I have my max bolus set to 1U. If I enter 1.2 it won't let me bolus. (The button gets grey)

**Comment by robinwo** [comment]
Updated & restriction now works! Thanks.
