### ISSUE TITLE
Calendar IOB and COB showing Zero

### ISSUE THREAD

**Issue by FlorinBv** [Artificial-Pancreas/iAPS#819]
Since Dev 5.1.0, the calendar shows zero COB and IOB, when IOB is positive.
![image](https://github.com/user-attachments/assets/e2079375-e1e2-4dcd-8e5b-65ed574ff79c)
![image](https://github.com/user-attachments/assets/89b305b6-a52d-4607-a21f-7aa2fd3cf86c)

**Comment by Jon-b-m** [comment]
Fixed in dev
