### ISSUE TITLE
CGM Switch Form g7 to g6

### ISSUE THREAD

**Issue by hirschthomas** [Artificial-Pancreas/iAPS#837]
CGM Change and no more updates possible !

Use DEV Version

**Comment by Merkaffe** [comment]
I need the all the details spelled out please. 
Are you using iOS 18 beta? There are currently several iOS 18 specific iAPS setting bugs.

**Comment by Jon-b-m** [comment]
I need the all the details spelled out please.
Are you using iOS 18 beta? There are currently several iOS 18 specific iAPS setting bugs.

**Comment by hirschthomas** [comment]
ok i am using iOS 18 Beta...

**Comment by Merkaffe** [comment]
> ok i am using iOS 18 Beta...

You still haven't described your issue?
