### ISSUE TITLE
Display shows open loop when closed

### ISSUE THREAD

**Issue by pheltzel** [Artificial-Pancreas/iAPS#842]
- Using dev v5.1.0(83)
- Saw loop was open at 1:30 p.m. (attached log) 
- Selected "Closed loop" in Settings
- At about 4:27 p.m. I noticed the display showed open again though I hadn't changed the setting. (Screenshot and log attached).
[8-30-24-4-28-PM-log.txt](https://github.com/user-attachments/files/16821898/8-30-24-4-28-PM-log.txt)
[8-30-24-log-1-30-PM.txt](https://github.com/user-attachments/files/16821899/8-30-24-log-1-30-PM.txt)
![IMG_0267](https://github.com/user-attachments/assets/a8540672-e80c-478d-8dd9-e63931af62df)

**Comment by pheltzel** [comment]
Nightscout shows basal adjustments, so maybe just a display issue?
https://pheltzel.my.nightscoutpro.com/

**Comment by Merkaffe** [comment]
From the NS it looks like the Loop was closed at 10:30 PM 30/8, UTC + 1 time, does that sound correct?

**Comment by pheltzel** [comment]
That’s right, thabks. And then I looked at it, about 3 hours later; and the
screen showed “Open” again.

Very possibly user error, but I  intentionally deselect Closer loop in
Settings.

**Comment by Jon-b-m** [comment]
@pheltzel but "deselecting closed loop" means enabling open loop, right?

**Comment by pheltzel** [comment]
Yes, sorry, typed the reply on a phone and it didn't make sense. 

I haven't seen this happen again. But for some reason the system was showing an "Open" message when I had selected "Closed loop." The first time it happened, I thought I might have accidentally deselected "Closed loop." But then I made sure to set it to "Closed loop" and 3 hours later, the main screen showed "Open" again.
