### ISSUE TITLE
Profile failing to disable “Change CR” when CR toggle off

### ISSUE THREAD

**Issue by macconnellk** [Artificial-Pancreas/iAPS#890]
When creating a profile that adjusts basal and ISF, but not CR, I am toggling the following in Profile screen:
-More Options: On (reveal more toggles)
-Change ISF and CR: Off  (reveal ISF and CR toggles)
-ISF: On
-CR: Off

I expect CR to remain unchanged. However, despite toggling CR off the CR is still adjusted indicated in Enacted pop-up.

Example: When setting the profile slider to 105%, and toggling the above profile settings, CR is being adjusted 5% from 16.6 to 15.8

**Comment by Jon-b-m** [comment]
> When creating a profile that adjusts basal and ISF, but not CR, I am toggling the following in Profile screen: -More Options: On (reveal more toggles) -Change ISF and CR: Off (reveal ISF and CR toggles) -ISF: On -CR: Off
> 
> I expect CR to remain unchanged. However, despite toggling CR off the CR is still adjusted indicated in Enacted pop-up.
> 
> Example: When setting the profile slider to 105%, and toggling the above profile settings, CR is being adjusted 5% from 16.6 to 15.8

Hi! I just tested again. It works for me. Are you using latest main or dev iAPS version?

**Comment by Jon-b-m** [comment]
Can I see your pop-up and your CR settings, please?

**Comment by macconnellk** [comment]
I am on Main 5.0.2. Dynamic CR is not enabled. 

It looks like it is only happening for a saved Profile.  When I run it directly from the Profiles screen and hit start it's fine. When I save it as a preset I get the issue.  Screenshots attached.

![image](https://github.com/user-attachments/assets/865e00de-4d3d-4bf0-91e8-777a182876d0)

![image](https://github.com/user-attachments/assets/eaf9d5f6-b9af-41d2-87cc-ce158d0bd92d)

![image](https://github.com/user-attachments/assets/77072e74-f3df-4dee-8f82-18d57ce1293e)

![image](https://github.com/user-attachments/assets/75940a4a-be56-4493-be98-ce04224b2e8d)

**Comment by macconnellk** [comment]
First pop is from the saved profile 105% Basal/ISF above which indicates in the present that only ISF toggled. The CR is being changed.

2nd pop up is when the same giggles are run directly without using a saved preset.

**Comment by macconnellk** [comment]
The middleware were is because I deleted everything from middleware including the blank function. Wanted to ensure no middleware was at fault.

**Comment by Jon-b-m** [comment]
Thanks, this additional info is very helpful.

**Comment by Jon-b-m** [comment]
Will push a fix tonight

**Comment by Jon-b-m** [comment]
@macconnellk I've now made a PR to dev branch resolving this issue: https://github.com/Artificial-Pancreas/iAPS/pull/892
