### ISSUE TITLE
Feature Request: DynISF parameters statistics 

### ISSUE THREAD

**Issue by naromero77** [Artificial-Pancreas/iAPS#897]
During visits with a physician, they will ask for pump settings: basal rates, ISF, and CR. In the U.S., it is basically required to provide these during a visit even if the doctor doesn't do anything to adjust them. Normally I would just provide the values from Autotune, but DynISF with autotune is problematic.

It would be helpful to have the following for DynISF in a simple screen that is understandable by a physician: Basal rate, ISF, and CR average over say 30 days. Also a visual plot to show the distribution of these values.

**Comment by Jon-b-m** [comment]
Average of ISF and CR can be computed,  but not for the basal rates as  these are currently not saved in storage for 30 days. However for the basal rates you can look at the AT:ed or your normal profile rates, when needed, as mentioned.

**Comment by Jon-b-m** [comment]
I think this is appropriate to be displayed in the dynamic settings perhaps?

**Comment by Jon-b-m** [comment]
Something like this:

![IMG_6871](https://github.com/user-attachments/assets/0defe1a1-aa8b-4f75-b432-71df9cb7142f)

**Comment by naromero77** [comment]
> Average of ISF and CR can be computed, but not for the basal rates as these are currently not saved in storage for 30 days. However for the basal rates you can look at the AT:ed or your normal profile rates, when needed, as mentioned.

Yes, if you are using AT or a fixed schedule basal rate you can view the parameters in the corresponding screen. Dynamic ISF does have an adjust basal setting, so it would be useful to have average basal rate as well. But since we are not storing the last 30 days of basal rates, then it cannot be displayed.

**Comment by naromero77** [comment]
> I think this is appropriate to be displayed in the dynamic settings perhaps? Or in the ISF settings would perhaps be better...

I think on the Dynamic Settings screen is OK for now. It would be nice to have a single screen with all settings rather than distributed across multiple screens. But that is just a personal preference.

**Comment by naromero77** [comment]
> Something like this:
> 
> ![IMG_6871](https://private-user-images.githubusercontent.com/53905247/375746474-0defe1a1-aa8b-4f75-b432-71df9cb7142f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NTc2NzIsIm5iZiI6MTcyODY1NzM3MiwicGF0aCI6Ii81MzkwNTI0Ny8zNzU3NDY0NzQtMGRlZmUxYTEtYWE4Yi00Zjc1LWI0MzItNzFkZjljYjcxNDJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDE0MzYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzMjFkZTFhZDIzYjgzYjZkMWFkZmEzNTA0N2U2MDc1MmYxNDQzMjViMWI2NmI4ODExOWI1YjZiN2EwMmYzYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZGAcRFXxLjncxbzbsZqHygRfAEo9mPJlHz2qEcfsUGY)

This looks great to me. Having some kind of delta (standard deviation) would be icing on the cake as the say.
 Thanks Jon.

**Comment by Jon-b-m** [comment]
feature in dev branch now
