### ISSUE TITLE
Feature Request: Autosens Ratio on Main View

### ISSUE THREAD

**Issue by naromero77** [Artificial-Pancreas/iAPS#906]
AndroidAPS displayed the autosens ratio on the main view:
https://androidaps.readthedocs.io/en/latest/Getting-Started/Screenshots.html#visualization-of-dynamic-target-adjustment

I generally found the AndroidAPS main view to be information overload, but this is one of the pieces of information that I miss/

**Comment by Jon-b-m** [comment]
It already is in main View. Just tap the iAPS-pill whenever you want to see it.
