### ISSUE TITLE
Dana. Can't set any .14 basal rates.

### ISSUE THREAD

**Issue by Jon-b-m** [Artificial-Pancreas/iAPS#961]
You can set .13 and .15, but whenever you're trying to set a .14 basal rate. (0.14, 1.14, ... ) in Basal settings in iAPS with a Dana pump it can't be set from iAPS, instead it's converted to a 0 U/h setting. Or actually it *is* saved to pump, but in iAPS it gets saved as 0.

Not sure where the bug is at yet.

Tagging @bastiaanv.

**Comment by bastiaanv** [comment]
Like @Jon-b-m stated, the value is being set in the Dana pump, but it is also being set in the json:
```json
[
  {
    "minutes" : 0,
    "start" : "00:00:00",
    "rate" : 0.14000000000000002048
  },
  {
    "rate" : 0.08,
    "minutes" : 420,
    "start" : "07:00:00"
  }
]
```

This means that `BasalProfileEntry.init` function is malfunctioning. I believe it has to do with the lossless conversion of this decimal.

![Screenshot 2024-12-16 at 19 46 56](https://github.com/user-attachments/assets/a96e1691-5025-47cc-9f4d-bf9ebd09f48f)

My proposed change would be in FreeAps -> Sources -> Models -> BasalProfileEntry.swift:
```swift
let rate = try Decimal(floatLiteral: container.decode(Double.self, forKey: .rate))
```
See https://github.com/Artificial-Pancreas/iAPS/pull/1004
