### ISSUE TITLE
Dynamic ISF average -- possible bug

### ISSUE THREAD

**Issue by naromero77** [Artificial-Pancreas/iAPS#963]
In a previous PR, average ISF and average CR are displayed on the Dynamic ISF menu near the bottom. I never see the average CR value change on this menu. Two requests:
1. A second look to make sure there is no bug in the average CR code
2. For the CR, it would be helpful to have the first decimal point after the integer. As in 12.5 for example, instead of 13.

**Comment by Jon-b-m** [comment]
> In a previous PR, average ISF and average CR are displayed on the Dynamic ISF menu near the bottom. I never see the average CR value change on this menu. Two requests:
> 
> 1. A second look to make sure there is no bug in the average CR code
> 2. For the CR, it would be helpful to have the first decimal point after the integer. As in 12.5 for example, instead of 13.

It's not a bug. The averages are based on new data (previously not saved) and therefore you need some time before these averages are displayed here. The CR is using one fraction digit currently: 
![image](https://github.com/user-attachments/assets/db82c4b5-3dea-4dbf-ae41-91fbe3ce4f4b)

**Comment by naromero77** [comment]
For the decimal point issue, we use mg/dL units and there is nothing to the right of the decimal point.

**Comment by naromero77** [comment]
![image](https://github.com/user-attachments/assets/e2d5512a-1236-4fc1-9757-27509456de7a)

**Comment by Jon-b-m** [comment]
Ah, thank you. I'll puh a fix to dev now.

**Comment by Jon-b-m** [comment]
Fixed here https://github.com/Artificial-Pancreas/iAPS/commit/14256c66f4c99a011eaa07258e57d8233d072320
