### ISSUE TITLE
Secondary TIR statistics line

### ISSUE THREAD

**Issue by mountrcg** [Artificial-Pancreas/iAPS#97]
The more detailed TIR statistics underneath the graph is not showing all intervals in dev 2.1.7

![IMG_5843](https://github.com/Artificial-Pancreas/iAPS/assets/539276/35732ad9-d48e-4f85-8b9f-bf126698e7c7)

**Comment by Jon-b-m** [comment]
Pushed to dev

**Comment by mountrcg** [comment]
I saw the code for regular range, just no output

**Comment by Jon-b-m** [comment]
> I saw the code for regular range, just no output

I don't understand?
